const ritualsData = [
  // ── 1. Griha & Property Pujas (10) ──
  {
    pujaName: 'Griha Pravesh Puja',
    slug: 'griha-pravesh-puja',
    category: 'Griha & Property Pujas',
    description: 'A comprehensive housewarming ceremony performed before moving into a new home. It purifies the living space, dispels negative energy, and seeks blessings from deities for happiness and prosperity.',
    shortDescription: 'Traditional housewarming ceremony for entering a new home.',
    duration: '3-4 hours',
    durationMinutes: 210,
    requiredMaterials: ['Kalash', 'Mango leaves', 'Coconut', 'Kumkum', 'Turmeric', 'Rice', 'Ghee', 'Havan Samagri', 'Flowers', 'Panchamrit'],
    estimatedMaterialCost: 1800,
    priceRange: { min: 3500, max: 8500 },
    locationType: 'Home',
    featured: true,
    popular: true,
    searchKeywords: ['housewarming', 'new home', 'home entry', 'vastu', 'graha pravesh', 'grihapravesh', 'entering house'],
    occasionTags: ['New Home', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Bhumi Puja',
    slug: 'bhumi-puja',
    category: 'Griha & Property Pujas',
    description: 'Performed before starting construction on a piece of land to seek permission and blessings from Mother Earth (Bhumi Devi) and Vaastu Purush.',
    shortDescription: 'Sanctifying land before starting house construction.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Bricks', 'Coconut', 'Flowers', 'Betel leaves', 'Navadhanya (9 grains)', 'Ghee', 'Turmeric', 'Kumkum'],
    estimatedMaterialCost: 1200,
    priceRange: { min: 3100, max: 6500 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['land purchase', 'construction', 'plot puja', 'foundation', 'bhumi devi', 'new build'],
    occasionTags: ['New Home'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Vastu Shanti Puja',
    slug: 'vastu-shanti-puja',
    category: 'Griha & Property Pujas',
    description: 'Conducted to rectify any architectural or structural defects (Vastu Doshas) in a home or commercial property, bringing harmony, health, and peace.',
    shortDescription: 'Ritual to remove architectural defects and bring home harmony.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Vastu Yantra', 'Havan Kund', 'Wood', 'Ghee', 'Flowers', 'Sweets', 'Panchamrit', 'Gangajal'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 4000, max: 9000 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['vastu dosh', 'home peace', 'architectural defect', 'vastu shanti', 'harmony', 'energy check'],
    occasionTags: ['New Home', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Office Inauguration Puja',
    slug: 'office-inauguration-puja',
    category: 'Griha & Property Pujas',
    description: 'An auspicious ritual performed before starting a new business, opening a shop, or moving into a new office space to invoke success, growth, and wealth.',
    shortDescription: 'Blessing ceremony for a new office, shop, or startup.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Ganesh idol', 'Lakshmi photo', 'Red thread', 'Flowers', 'Sweets', 'Coconut', 'Incense', 'Camphor'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2500, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['new office', 'shop opening', 'inauguration', 'business startup', 'workplace', 'new business'],
    occasionTags: ['Business Opening', 'Career Growth', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Dwar Puja',
    slug: 'dwar-puja',
    category: 'Griha & Property Pujas',
    description: 'Performed at the main entrance door of a newly rented or bought house to prevent evil spirits or negative vibes from entering the premises.',
    shortDescription: 'Sanctification of the main entrance door of a house.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Mango leaves garland', 'Kumkum', 'Turmeric', 'Coconut', 'Flowers', 'Oil lamp'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['door entry', 'entrance puja', 'protection', 'threshold', 'main gate'],
    occasionTags: ['New Home', 'Protection'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Shila Nyas Puja',
    slug: 'shila-nyas-puja',
    category: 'Griha & Property Pujas',
    description: 'The formal foundation stone-laying ceremony for large structures, temples, or residential complexes, seeking divine support for completion without obstacles.',
    shortDescription: 'Foundation stone laying ceremony for construction.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Foundation stone', 'Five metals (Panchadhatu)', 'Navadhanya', 'Sandalwood paste', 'Flowers'],
    estimatedMaterialCost: 3000,
    priceRange: { min: 5000, max: 12000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['foundation stone', 'construction start', 'stone laying', 'masonry', 'building foundation'],
    occasionTags: ['New Home'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Boring / Water Well Puja',
    slug: 'boring-water-well-puja',
    category: 'Griha & Property Pujas',
    description: 'Ritual performed to bless the earth before boring for groundwater or digging a well, praying for abundance of clean water and safety of the workers.',
    shortDescription: 'Ritual performed before digging a well or groundwater boring.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Coconut', 'Flowers', 'Camphor', 'Betel nuts', 'Saffron', 'Rice grains'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1800, max: 3500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['water boring', 'tube well', 'well digging', 'groundwater', 'boring puja'],
    occasionTags: ['New Home', 'Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Bhoomi Homa',
    slug: 'bhoomi-homa',
    category: 'Griha & Property Pujas',
    description: 'A sacred fire ritual dedicated to Mother Earth (Bhoomi Devi) to seek forgiveness for any ecological disruptions during construction and purify the soil.',
    shortDescription: 'Sacred fire ritual to bless the land and purify the soil.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Havan Samagri', 'Ghee', 'Bhoomi Devi photo', 'Flowers', 'Herbs', 'Clay pot'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3500, max: 7000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['earth fire', 'purification', 'land Homa', 'bhoomi devi', 'soil blessing'],
    occasionTags: ['New Home'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Property Sale Puja',
    slug: 'property-sale-puja',
    category: 'Griha & Property Pujas',
    description: 'A special prayer performed to remove obstacles in selling a plot, building, or house, invoking Vyasa and Lord Ganesha to attract suitable buyers.',
    shortDescription: 'Prayers to clear obstacles for selling land or house.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Clay lamp', 'Rice', 'Flowers', 'Sandalwood', 'Turmeric', 'Coconut', 'Yellow cloth'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['selling property', 'real estate sale', 'remove obstacles', 'buyer attraction', 'sell house'],
    occasionTags: ['Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Gruha Pravesha Homa',
    slug: 'gruha-pravesha-homa',
    category: 'Griha & Property Pujas',
    description: 'An elaborate homa performed specifically in Karnataka alongside housewarming, including Vastu Homa and Navadhanya Homa to bring ultimate auspiciousness.',
    shortDescription: 'Traditional Karnataka-style housewarming fire ceremony.',
    duration: '4 hours',
    durationMinutes: 240,
    requiredMaterials: ['Mango leaves', 'Havan samagri', 'Navadhanya', 'Panchamrit', 'Ghee', 'Coconuts', 'Sweets'],
    estimatedMaterialCost: 2500,
    priceRange: { min: 5000, max: 11000 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['karnataka housewarming', 'gruhapravesha', 'vastu homa', 'new home fire'],
    occasionTags: ['New Home', 'Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },

  // ── 2. Marriage & Family Rituals (9) ──
  {
    pujaName: 'Vedic Wedding (Vivaha)',
    slug: 'vedic-wedding-vivaha',
    category: 'Marriage & Family Rituals',
    description: 'A traditional and complete Vedic Hindu marriage ceremony comprising the Saptapadi (seven steps), Kanyadaan, Mangalsutra dharana, and Panigrahana.',
    shortDescription: 'Complete traditional Vedic marriage and wedding ceremony.',
    duration: '5 hours',
    durationMinutes: 300,
    requiredMaterials: ['Mandap decor', 'Havan Kund', 'Garlands', 'Mangalsutra', 'Sindoor', 'Rice', 'Betel leaves', 'Ghee', 'Coconuts', 'Sweets'],
    estimatedMaterialCost: 5000,
    priceRange: { min: 11000, max: 45000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['marriage', 'wedding', 'shaadi', 'matrimony', 'sacred vows', 'saptapadi', 'vivaha'],
    occasionTags: ['Marriage'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Satyanarayana Swamy Vrata',
    slug: 'satyanarayana-swamy-vrata',
    category: 'Marriage & Family Rituals',
    description: 'A highly sacred ritual dedicated to Lord Satyanarayana (Lord Vishnu), performed extensively in Karnataka for family welfare, removal of struggles, and general success.',
    shortDescription: 'Very popular devotional worship of Lord Satyanarayana for peace and prosperity.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Satyanarayana photo', 'Sava-seru Wheat Rava (1.25 measures)', 'Panchamrit', 'Banana trunks', 'Flowers', 'Betel leaves'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 2500, max: 6000 },
    locationType: 'Home',
    featured: true,
    popular: true,
    searchKeywords: ['satyanarayan vrata', 'karnataka satyanarayana', 'purnima katha', 'family prosperity', 'vishnu puja'],
    occasionTags: ['Prosperity', 'Health'],
    supportedRegions: ['Karnataka', 'Andhra Pradesh', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Sagai (Engagement Ceremony)',
    slug: 'sagai-engagement-ceremony',
    category: 'Marriage & Family Rituals',
    description: 'The formal engagement ceremony in Hindu culture, where couples exchange rings and families exchange gifts, sanctified by prayers to Lord Ganesha and Varuna.',
    shortDescription: 'Formal pre-wedding engagement and ring exchange ceremony.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Rings', 'Sweets', 'Fruits', 'Kumkum', 'Roli', 'Coconut', 'Flowers', 'Red cloth'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['engagement', 'ring ceremony', 'sagai', 'mangni', 'pre-wedding', 'promise'],
    occasionTags: ['Marriage'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Gauri Shankar Puja',
    slug: 'gauri-shankar-puja',
    category: 'Marriage & Family Rituals',
    description: 'Conducted for marital harmony, seeking the blessings of Lord Shiva and Goddess Parvati (Gauri) to remove misunderstandings and ensure longevity of the marriage.',
    shortDescription: 'Worship of Shiva and Parvati for marital harmony and love.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Shiva Parvati idol/photo', 'Red dupatta', 'Flowers', 'Fruits', 'Sindoor', 'Betel nuts', 'Sweets'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2200, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['marriage harmony', 'shiva parvati', 'marital peace', 'relationship', 'family union'],
    occasionTags: ['Marriage', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Roka Ceremony Puja',
    slug: 'roka-ceremony-puja',
    category: 'Marriage & Family Rituals',
    description: 'The first step towards a wedding where both families declare their consent. Sacred hymns and Ganesh prayers are held to bless the alliance.',
    shortDescription: 'First formal wedding alliance ceremony between families.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Dry fruits', 'Sweets', 'Coconut', 'Kumkum', 'Rice', 'Red thread', 'Flowers'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['roka', 'alliance', 'marriage consent', 'pre wedding', 'first agreement'],
    occasionTags: ['Marriage'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Varshik Shraddh',
    slug: 'varshik-shraddh',
    category: 'Marriage & Family Rituals',
    description: 'An annual ritual to pay respects to deceased parents or ancestors, bringing peace and descendant blessings to the family.',
    shortDescription: 'Annual ancestor remembrance and food offering ritual.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Black sesame seeds', 'Barley', 'Rice balls (Pinda)', 'White flowers', 'Kusha grass', 'Ghee', 'Honey'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2500, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['ancestor worship', 'death anniversary', 'pinda daan', 'shraddha', 'pitru', 'remembrance'],
    occasionTags: ['Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Kanya Daan Ceremony',
    slug: 'kanya-daan-ceremony',
    category: 'Marriage & Family Rituals',
    description: 'The highly emotional wedding ritual of "giving away the daughter" to the groom, symbolizing transfer of responsibility and generation of high spiritual merits.',
    shortDescription: 'Traditional ritual of giving away the daughter in marriage.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Holy water pot', 'Gold ornament', 'Saffron', 'Rice', 'Flowers', 'Betel leaves'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3000, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kanyadaan', 'wedding gift', 'wedding ritual', 'daughter wedding', 'giving hand'],
    occasionTags: ['Marriage'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Tulasi Vivaha',
    slug: 'tulasi-vivaha',
    category: 'Marriage & Family Rituals',
    description: 'The ceremonial wedding of the Tulasi plant (Holy Basil) with Lord Shaligram (Vishnu), signifying the start of the Hindu wedding season in Karthika month.',
    shortDescription: 'Ceremonial marriage of Holy Basil (Tulasi) with Lord Vishnu.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Tulasi plant pot', 'Shaligram/Vishnu photo', 'Sringar items for Tulasi', 'Sugarcane stalks', 'Garlands', 'Amla branches'],
    estimatedMaterialCost: 800,
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['tulsi wedding', 'karthika vivaha', 'shaligram marriage', 'tulasi habba', 'holy basil'],
    occasionTags: ['Marriage', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Vat Savitri Puja',
    slug: 'vat-savitri-puja',
    category: 'Marriage & Family Rituals',
    description: 'Performed by married women, praying for the long life and health of their husbands by tying sacred threads around a Banyan tree.',
    shortDescription: 'Worship of Savitri and Banyan tree for husband\'s longevity.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Banyan tree thread', 'Wet chickpeas', 'Sweets', 'Fruits', 'Sindoor', 'Bangles', 'Red thread'],
    estimatedMaterialCost: 400,
    priceRange: { min: 1100, max: 2500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['husband long life', 'savitri vrat', 'banyan tree', 'married women', 'protection husband'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },

  // ── 3. Child & Sanskar Ceremonies (10) ──
  {
    pujaName: 'Naamkaran Sanskar',
    slug: 'naamkaran-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The traditional naming ceremony for a newborn, typically performed on the 11th or 12th day after birth to invite positive vibrations.',
    shortDescription: 'Traditional Hindu naming ceremony for newborn babies.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Honey', 'Ghee', 'Sacred thread', 'New baby clothes', 'Rice grains', 'Betel leaves', 'Flowers', 'Ganesh photo'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['naming ceremony', 'newborn baby', 'naming child', 'naamkaran', 'sanskar', 'child birth', 'baby name'],
    occasionTags: ['Child Birth'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Mundan Sanskar (Tonsure)',
    slug: 'mundan-sanskar-tonsure',
    category: 'Child & Sanskar Ceremonies',
    description: 'The first shaving of a child\'s hair (tonsure) to cleanse the child from past-life karma and stimulate healthy brain and hair growth.',
    shortDescription: 'First tonsure or head shaving ceremony of the child.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Turmeric paste', 'Curd', 'Honey', 'Barber\'s new razor', 'Coconut', 'Flowers', 'Panchamrit'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['tonsure', 'baby haircut', 'shaving head', 'mundan', 'child ceremony', 'hair cutting', 'cleansing'],
    occasionTags: ['Child Birth', 'Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Upanayana (Janeu Ceremony)',
    slug: 'upanayana-janeu-ceremony',
    category: 'Child & Sanskar Ceremonies',
    description: 'The sacred thread ceremony marking the initiation of a young boy into formal education and spiritual responsibilities under Vedic traditions.',
    shortDescription: 'Sacred thread initiation and Vedic education start ceremony.',
    duration: '4 hours',
    durationMinutes: 240,
    requiredMaterials: ['Janeu threads', 'Deer skin seat', 'Alms bag', 'Wood for Havan', 'New yellow garments', 'Sandalwood'],
    estimatedMaterialCost: 2500,
    priceRange: { min: 7500, max: 15000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['sacred thread', 'janeu', 'upanayan', 'spiritual initiation', 'boy ceremony', 'thread ceremony', 'muni thread'],
    occasionTags: ['Education', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Annaprashan Sanskar',
    slug: 'annaprashan-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The ceremony marking the infant\'s first intake of solid food (typically sweet rice pudding or kheer), invoking nutritional health and digestion.',
    shortDescription: 'First solid food feeding ceremony of the baby.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Silver bowl & spoon', 'Kheer (rice pudding)', 'Honey', 'Ganga water', 'Flowers', 'Ganesh Puja kit'],
    estimatedMaterialCost: 800,
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['first solid food', 'feeding baby', 'kheer feeding', 'annaprashan', 'baby health food'],
    occasionTags: ['Child Birth', 'Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Garbh Sanskar / Seemantonayana',
    slug: 'garbh-sanskar-seemantonayana',
    category: 'Child & Sanskar Ceremonies',
    description: 'A baby shower-like Vedic ceremony performed during pregnancy to bless the expectant mother and invite healthy, intelligent, and positive qualities in the fetus.',
    shortDescription: 'Vedic baby shower pregnancy blessing for child and mother.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Red saree', 'Fruits', 'Sweets', 'Havan items', 'Aromatic oils', 'Coconut', 'Ghee'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3000, max: 6000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['pregnancy puja', 'baby shower', 'garbh sanskar', 'safe delivery', 'mother blessing', 'child birth blessing'],
    occasionTags: ['Child Birth', 'Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Karnavedha Sanskar',
    slug: 'karnavedha-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The ear-piercing ceremony for children, believed to improve memory power, physical health, and protect from diseases.',
    shortDescription: 'Traditional ear-piercing ceremony for memory and health.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Gold/silver needle', 'Coconut oil', 'Turmeric', 'Cotton', 'Flowers', 'Sweets'],
    estimatedMaterialCost: 400,
    priceRange: { min: 1100, max: 2500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['ear piercing', 'karnavedha', 'earlobe piercing', 'child health', 'acupuncture'],
    occasionTags: ['Child Birth', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Vidyarambh Sanskar',
    slug: 'vidyarambh-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'Initiation of writing letters and learning. Children write their first letters in a tray of rice grains, seeking blessings of Goddess Saraswati.',
    shortDescription: 'Ritual marking the initiation of education and writing.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Slate/Notebook', 'Chalk/Pen', 'Rice grains tray', 'Saraswati photo', 'White flowers', 'Modak'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1200, max: 2800 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['starting school', 'education start', 'saraswati write', 'vidyarambh', 'writing letters', 'kid schooling'],
    occasionTags: ['Education'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Jatakarma Sanskar',
    slug: 'jatakarma-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'A birth ritual performed immediately after the child is born to welcome the infant, where the father feeds a drop of ghee and honey to the baby.',
    shortDescription: 'Post-birth welcoming ritual of baby by the father.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Pure forest honey', 'Desi cow ghee', 'Gold stick/spoon', 'Gangajal', 'Dharba grass'],
    estimatedMaterialCost: 300,
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['birth ritual', 'father feeding', 'jatakarma', 'newborn baby', 'first touch'],
    occasionTags: ['Child Birth'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Nishkramana Sanskar',
    slug: 'nishkramana-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The child\'s first formal outing into the open air and sunlight, typically done in the 3rd or 4th month to worship the Sun and Moon.',
    shortDescription: 'Infant\'s first outing to worship sun and moon.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Sun/Moon photos', 'Conch shell', 'Curd', 'Honey', 'Rice grains', 'Fresh flowers'],
    estimatedMaterialCost: 400,
    priceRange: { min: 1200, max: 2500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['first outing', 'sun worship', 'moon worship', 'nishkramana', 'baby outdoors'],
    occasionTags: ['Child Birth', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Chudakarana Sanskar',
    slug: 'chudakarana-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'Performed to shave the child\'s head leaving a single tuft of hair (chuda/shikha) at the crown, which guards the brain\'s spiritual energy center.',
    shortDescription: 'Spiritual head shaving ceremony leaving a crown tuft.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Kusha grass', 'Turmeric powder', 'Sandalwood', 'Ghee', 'Barber tools', 'New yellow cloth'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['shikha tuft', 'chudakarana', 'tonsure hair', 'spiritual health', 'shikha ceremony'],
    occasionTags: ['Child Birth', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },

  // ── 4. Business & Career Pujas (8) ──
  {
    pujaName: 'Business Ganesh Puja',
    slug: 'business-ganesh-puja',
    category: 'Business & Career Pujas',
    description: 'Dedicated to Lord Ganesha, this puja removes startup hurdles, protects business assets from litigation/losses, and boosts profitability.',
    shortDescription: 'Obstacle removal puja for shop, factory, or corporate start.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Ganesh Idol', 'Durva grass', 'Modak sweets', 'Red flowers', 'Coconut', 'Betel leaves', 'Attar perfume'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2100, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['business start', 'ganesha business', 'remove blocks', 'profit puja', 'ganesh puja', 'business opening', 'shop success'],
    occasionTags: ['Business Opening', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Lakshmi Kuber Puja',
    slug: 'lakshmi-kuber-puja',
    category: 'Business & Career Pujas',
    description: 'Invokes Goddess Lakshmi and Lord Kuber (treasurer of gods) to bring cash flow, wealth accumulation, and financial security to individuals and businesses.',
    shortDescription: 'Auspicious puja for wealth attraction and financial growth.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Kuber Yantra', 'Lakshmi silver coin', 'Lotus flowers', 'Perfume', 'Makhana sweets', 'Clarified butter (Ghee)'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3500, max: 8000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['wealth puja', 'kuber coin', 'money block', 'financial growth', 'lakshmi puja', 'wealth creation', 'business growth'],
    occasionTags: ['Business Opening', 'Prosperity', 'Career Growth'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Vyapar Vriddhi Puja',
    slug: 'vyapar-vriddhi-puja',
    category: 'Business & Career Pujas',
    description: 'Specifically designed for shopkeepers and corporate office owners to attract more footfall, increase sales, and defeat competitors.',
    shortDescription: 'Puja to enhance customer flow and increase sales.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Vyapar Vriddhi Yantra', 'Saffron', 'Camphor', 'Fresh fruits', 'Betel nuts', 'Incense cones'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['sales growth', 'business success', 'shop puja', 'client attraction', 'increase footfall', 'commercial'],
    occasionTags: ['Business Opening', 'Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Vishwakarma Puja',
    slug: 'vishwakarma-puja',
    category: 'Business & Career Pujas',
    description: 'Performed on Vishwakarma Jayanti to worship machines, tools, instruments, computers, and vehicles. It ensures working safety and prevents machinery breakdowns.',
    shortDescription: 'Industrial and office machine worship for safety and work.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Vishwakarma photo', 'Tools/Machines', 'Red-yellow threads', 'Sweets', 'Flowers', 'Incense'],
    estimatedMaterialCost: 700,
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['factory puja', 'machine worship', 'tool blessing', 'engineers day', 'industrial', 'vehicle puja', 'computers'],
    occasionTags: ['Business Opening', 'Protection'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Saraswati Puja for Career',
    slug: 'saraswati-puja-for-career',
    category: 'Business & Career Pujas',
    description: 'Ideal for students preparing for competitive exams or professionals looking for career shifts, promotions, and academic success.',
    shortDescription: 'Intellectual blessing for exams, promotion, and new skills.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['White clothes', 'Saraswati Idol', 'Books/Pens', 'White flowers', 'Yellow rice', 'Honey', 'Curd'],
    estimatedMaterialCost: 800,
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['exam success', 'job promotion', 'career growth', 'saraswati book', 'clear memory', 'passing test', 'education'],
    occasionTags: ['Education', 'Career Growth'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Shani Dev Puja for Job Stability',
    slug: 'shani-dev-puja-for-job-stability',
    category: 'Business & Career Pujas',
    description: 'Worship of Lord Shani to secure employment, safeguard against sudden layoffs, resolve disputes with seniors, and find a desired job.',
    shortDescription: 'Prayers to Lord Shani Dev for career protection and job security.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Mustard oil', 'Black cloth', 'Black sesame', 'Iron ring', 'Blue flowers', 'Urad dal'],
    estimatedMaterialCost: 600,
    priceRange: { min: 2100, max: 4800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['job stability', 'layoff protection', 'shani job', 'career hurdle', 'boss problems', 'protection'],
    occasionTags: ['Career Growth', 'Protection'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Surya Puja for Promotion',
    slug: 'surya-puja-for-promotion',
    category: 'Business & Career Pujas',
    description: 'Dedicated to Lord Surya (Sun) to earn fame, administrative authority, government jobs, promotions, and goodwill from bosses.',
    shortDescription: 'Sun worship to invite authority, reputation, and promotions.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Copper pot', 'Red sandalwood', 'Red flowers', 'Jaggery', 'Wheat grains', 'Roli'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1800, max: 3800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['government job', 'promotion', 'authority', 'sun worship', 'fame', 'reputation boost', 'career growth'],
    occasionTags: ['Career Growth', 'Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Chandra Puja for Business Peace',
    slug: 'chandra-puja-for-business-peace',
    category: 'Business & Career Pujas',
    description: 'Performed to pacify the Moon (Chandra), which governs emotional stability and decision-making, helping business partners resolve internal conflicts.',
    shortDescription: 'Moon deity worship for calm business partnership decisions.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['White sandalwood', 'Milk', 'Rice grains', 'Camphor', 'White lotus', 'Conch shell'],
    estimatedMaterialCost: 600,
    priceRange: { min: 2000, max: 4200 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['partner conflict', 'business peace', 'moon cooling', 'clear decision', 'cool mind'],
    occasionTags: ['Prosperity', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },

  // ── 5. Health & Protection Pujas (7) ──
  {
    pujaName: 'Maha Mrityunjaya Jaap',
    slug: 'maha-mrityunjaya-jaap',
    category: 'Health & Protection Pujas',
    description: 'A powerful chanting of the Maha Mrityunjaya mantra dedicated to Lord Shiva, done to recover from critical illness, avert untimely end, and build life force.',
    shortDescription: 'Life-saving Shiva mantra chanting for heavy health recovery.',
    duration: '5 hours',
    durationMinutes: 300,
    requiredMaterials: ['Rudraksha mala', 'Bel leaves', 'Milk', 'Honey', 'Ghee', 'Incense', 'Havan wood', 'Black sesame'],
    estimatedMaterialCost: 3000,
    priceRange: { min: 5500, max: 15000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['health recovery', 'cure illness', 'shiva health', 'mrityunjay', 'long life', 'protection', 'fear of death', 'disease recovery'],
    occasionTags: ['Health', 'Protection'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Dhanvantari Puja',
    slug: 'dhanvantari-puja',
    category: 'Health & Protection Pujas',
    description: 'Worship of Lord Dhanvantari, the physician of gods and source of Ayurveda, for relief from chronic body pains, mental health disorders, and physical ailments.',
    shortDescription: 'Devotional prayers to God of Healing for absolute wellbeing.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Dhanvantari photo', 'Yellow flowers', 'Tulsi leaves', 'Medicinal herbs', 'Honey', 'Yellow cloth'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['ayurveda god', 'healing body', 'chronic pain', 'doctor blessing', 'dhanwantari', 'good health', 'disease cure'],
    occasionTags: ['Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Durga Kavach Path',
    slug: 'durga-kavach-path',
    category: 'Health & Protection Pujas',
    description: 'Recitation of the armor of Goddess Durga (Kavach) to create a protective spiritual shield around the devotee, keeping away accidents, evil eyes, and negative vibes.',
    shortDescription: 'Recitation of Durga armor for protective shielding.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Durga photo', 'Red flowers', 'Lemon garland', 'Camphor', 'Sweets', 'Sindoor'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['protective shield', 'evil eye', 'black magic removal', 'durga armor', 'accident safety', 'protection', 'fear relief'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Hanuman Chalisa Path & Puja',
    slug: 'hanuman-chalisa-path-puja',
    category: 'Health & Protection Pujas',
    description: 'Chanting of Hanuman Chalisa 108 times, invoking Lord Hanuman for physical strength, courage, mental sanity, and removal of fears.',
    shortDescription: '108 chants of Hanuman Chalisa for courage and mental strength.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Hanuman idol', 'Sindoor (orange)', 'Jasmine oil', 'Laddoo sweets', 'Basil leaves', 'Red flag'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['courage', 'strength', 'hanuman chalisa', 'fear removal', 'bajrang bali', 'ghost defense', 'protection', 'good health'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Subrahmanya Puja',
    slug: 'subrahmanya-puja',
    category: 'Health & Protection Pujas',
    description: 'Dedicated to Lord Subrahmanya (Kartikeya), worshiped in Karnataka to heal skin diseases, resolve family delays, and gain protection from negative energies.',
    shortDescription: 'Traditional Kartikeya worship for skin health and protection.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Subrahmanya photo', 'Red flowers', 'Milk for abhisheka', 'Snake clay model', 'Fruits', 'Sandalwood'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['subramanya swamy', 'kukke karthikeya', 'skin disease cure', 'snakes', 'protection', 'shashti puja'],
    occasionTags: ['Health', 'Protection'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Sudarsana Archana',
    slug: 'sudarsana-archana',
    category: 'Health & Protection Pujas',
    description: 'Devotional chanting of Sudarsana mantras with flower offering, seeking Lord Vishnu\'s weapon protection to clear professional jealousies and obstacles.',
    shortDescription: 'Vishnu weapon disk prayers to remove career obstacles.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Sudarshana photo/Yantra', 'Red flowers', 'Tulsi leaves', 'Sweets', 'Incense', 'Ghee lamp'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1800, max: 3500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['sudarshana chakra', 'jealousy clearing', 'career block removal', 'protection', 'vishnu disk'],
    occasionTags: ['Protection', 'Career Growth'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Dhanvantari Archana',
    slug: 'dhanvantari-archana',
    category: 'Health & Protection Pujas',
    description: 'A dedicated archana (flower offering) chanting Dhanvantari healing names, providing relief from chronic pain and requesting general family health.',
    shortDescription: 'Healing name chanting for patient recovery.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Yellow flowers', 'Tulsi', 'Sweets', 'Oil lamp', 'Fruits', 'Dhanvantari photo'],
    estimatedMaterialCost: 400,
    priceRange: { min: 1200, max: 2500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['patient healing', 'dhanvantari', 'medicine blessing', 'archana', 'good health'],
    occasionTags: ['Health'],
    supportedRegions: [],
    imageUrl: ''
  },

  // ── 6. Festival Pujas (15) ──
  {
    pujaName: 'Diwali Lakshmi Puja',
    slug: 'diwali-lakshmi-puja',
    category: 'Festival Pujas',
    description: 'Performed on Amavasya during Diwali. This puja invites wealth, luck, and brightness to homes and commercial setups for the upcoming year.',
    shortDescription: 'Diwali evening worship of Goddess Lakshmi for wealth.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Lakshmi-Ganesh clay idols', 'Clay diyas', 'Silver coin', 'Kori shells', 'Lotus seeds', 'Sweets (Kaju katli)'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3000, max: 6500 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['diwali', 'lakshmi puja', 'deepavali', 'wealth invitation', 'new year business', 'prosperity', 'wealth'],
    occasionTags: ['Prosperity', 'Wealth'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Ganesh Chaturthi Puja',
    slug: 'ganesh-chaturthi-puja',
    category: 'Festival Pujas',
    description: 'Celebrated during the Ganesh festival. Involves installing the clay idol of Ganesha, reciting stories, offering modaks, and requesting wisdom.',
    shortDescription: 'Clay idol installation and worship of Lord Ganesha.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Ganesh clay idol', 'Modaks (21)', 'Durva grass', 'Red flowers', 'Jaggery', 'Incense', 'Coconut'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2100, max: 5000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['ganeshutsav', 'ganpati sthapana', 'chaturthi', 'clay ganesha', 'modak offering', 'education', 'remove obstacles'],
    occasionTags: ['Education', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Varamahalakshmi Vrata',
    slug: 'varamahalakshmi-vrata',
    category: 'Festival Pujas',
    description: 'Highly celebrated festival by women in Karnataka on the Friday before full moon in Shravana month. Praying for long-life of husbands, kids, and gold flow.',
    shortDescription: 'Grand Karnataka festival honoring Goddess Lakshmi for family welfare.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Lakshmi face mask', 'Kalash pot', 'Sringaar sarees', 'Lotus flowers', 'Nine-knot thread', 'Coconuts', 'Sweets'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 3000, max: 7500 },
    locationType: 'Home',
    featured: true,
    popular: true,
    searchKeywords: ['varalakshmi vrata', 'karnataka shravan friday', 'gold puja', 'varamahalakshmi', 'married women festival', 'wealth', 'prosperity'],
    occasionTags: ['Prosperity', 'Wealth', 'Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Durga Puja / Ghatasthapana',
    slug: 'durga-puja-ghatasthapana',
    category: 'Festival Pujas',
    description: 'Performed on the first day of Navratri. Involves installing the holy pot (Kalash/Ghata) representing Goddess Durga, sowing barley seeds, and reciting prayers.',
    shortDescription: 'Navratri day-1 pot installation and barley sowing.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Clay pot', 'Barley seeds', 'Clean mud', 'Kalash water', 'Durga photo', 'Saptadhanya (7 grains)'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['navratri start', 'ghat sthapana', 'kalash installation', 'durga puja', 'nine nights', 'protection'],
    occasionTags: ['Protection', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Maha Shivratri Puja',
    slug: 'maha-shivratri-puja',
    category: 'Festival Pujas',
    description: 'Performed on Shivratri night, involving the continuous Abhishek of Shiva Lingam with milk, honey, sugarcane juice, and bel leaves to grant wish-fulfillment.',
    shortDescription: 'Shivratri night continuous Shiva abhishek and prayers.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Shiva Lingam', 'Bel leaves', 'Milk', 'Curd', 'Honey', 'Bhaang', 'Dhatura flowers', 'Sugarcane juice'],
    estimatedMaterialCost: 1200,
    priceRange: { min: 3100, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['shivratri abhishek', 'shiva night', 'wish fulfillment', 'dhatura', 'bhaang', 'health', 'protection'],
    occasionTags: ['Health', 'Protection', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Krishna Janmashtami Puja',
    slug: 'krishna-janmashtami-puja',
    category: 'Festival Pujas',
    description: 'Performed at midnight on Lord Krishna\'s birthday. Involves bathing Laddu Gopal with panchamrit, placing Him in a swing, and singing bhajans.',
    shortDescription: 'Midnight swing and baby Krishna birthday worship.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Laddu Gopal idol', 'Jhula (swing)', 'Panchamrit', 'Makhan-Mishri (butter mix)', 'Yellow clothes', 'Peacock feather'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['krishna birth', 'gokulashtami', 'swing lord', 'butter bhog', 'janmashtami', 'child health'],
    occasionTags: ['Child Birth', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Swarna Gowri Vrata',
    slug: 'swarna-gowri-vrata',
    category: 'Festival Pujas',
    description: 'Celebrated one day before Ganesh Chaturthi in Karnataka. Married and unmarried women worship Goddess Gowri (Parvati) for family unity and good spouses.',
    shortDescription: 'Karnataka festival worshiping Goddess Gowri for happy marriage.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Gowri clay idol', 'Bagina (marriage gifts)', 'Red thread', 'Sindoor', 'Betel leaves', 'Mora (bamboo trays)', 'Sweets'],
    estimatedMaterialCost: 1200,
    priceRange: { min: 2200, max: 5000 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['gowri habba', 'karnataka gowri puja', 'bagina offering', 'parvati worship', 'marriage luck'],
    occasionTags: ['Marriage', 'Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Ugadi Puja (Kannada New Year)',
    slug: 'ugadi-puja-kannada-new-year',
    category: 'Festival Pujas',
    description: 'Celebrated on the first day of Chaitra month. Marking Kannada New Year. Involves Panchanga reading, mango leaf decoration, and offering Ugadi Pachadi/Bevu Bella.',
    shortDescription: 'Kannada New Year prayers with Bevu Bella sharing.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Neem leaves & flowers', 'Jaggery', 'Mango leaves garland', 'Panchanga book', 'Coconuts', 'Obbattu sweets'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['kannada new year', 'ugadi bevu bella', 'panchanga sravanam', 'chaitra new year', 'prosperity start'],
    occasionTags: ['Prosperity', 'New Home'],
    supportedRegions: ['Karnataka', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Raksha Bandhan Puja',
    slug: 'raksha-bandhan-puja',
    category: 'Festival Pujas',
    description: 'A household prayer celebrating the bond of brothers and sisters, seeking longevity for brothers and safety for sisters.',
    shortDescription: 'Brother-sister thread tying prayer for safety and long life.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Rakhi threads', 'Roli', 'Chawal', 'Sweets', 'Diya plate', 'Coconut'],
    estimatedMaterialCost: 300,
    priceRange: { min: 1000, max: 2000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['rakhi tying', 'brother sister bond', 'family festival', 'shravan purnima', 'protection brother'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Karwa Chauth Vrat Udyapan',
    slug: 'karwa-chauth-vrat-udyapan',
    category: 'Festival Pujas',
    description: 'The closing ceremony (Udyapan) of Karwa Chauth fasts. Married women offer gifts and foods to other women and seek blessings for marital union.',
    shortDescription: 'Closing ritual for Karwa Chauth fasts for married women.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Clay pots (Karwa)', 'Sringar kit (makeup)', 'Sweets', 'Saree gift', 'Dry fruits', 'Sindoor'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 2500, max: 5000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['karva chauth', 'fasting end', 'udyapan', 'married women gifts', 'husband longevity'],
    occasionTags: ['Marriage', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Chhath Puja Surya Arghya',
    slug: 'chhath-puja-surya-arghya',
    category: 'Festival Pujas',
    description: 'The offering of water and prasad (Arghya) to the setting and rising Sun on river banks, praying for the wellbeing of children and family.',
    shortDescription: 'Surya Deva arghya offering on river bank.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Soop (bamboo tray)', 'Thekua sweets', 'Cane stalks', 'Raddish', 'Coconut', 'Vermillion'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['chhath puja', 'sun setting', 'river bank', 'thekua prasad', 'bihar festival', 'health children'],
    occasionTags: ['Health', 'Child Birth'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Holi Dahan Puja',
    slug: 'holi-dahan-puja',
    category: 'Festival Pujas',
    description: 'Performed in the evening before playing colors. Worshiping the bonfire (Holika) to burn down illness, greed, and negative habits.',
    shortDescription: 'Holika bonfire worship to purge diseases and negative habits.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Cow dung beads', 'Thread', 'Raw cotton', 'Jaggery', 'Turmeric', 'Coconut', 'Water pot'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['holika dahan', 'bonfire puja', 'good over evil', 'spring festival', 'burn disease'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Makar Sankranti Surya Tarpan',
    slug: 'makar-sankranti-surya-tarpan',
    category: 'Festival Pujas',
    description: 'A transit day puja thanking the Sun God for rich crops, involving the offering of sesame seeds and water (Tarpan).',
    shortDescription: 'Sankranti day crop thanksgiving and sun water offering.',
    duration: '1 hour',
    durationMinutes: 60,
    requiredMaterials: ['Black sesame', 'Copper pot', 'Rice', 'Jaggery sweets', 'Wheat', 'Yellow flowers'],
    estimatedMaterialCost: 400,
    priceRange: { min: 1200, max: 2500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['sun transit', 'sankranti', 'sesame offering', 'kite festival', 'crop thank'],
    occasionTags: ['Prosperity', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Hanuman Jayanti Sundarkand Path',
    slug: 'hanuman-jayanti-sundarkand-path',
    category: 'Festival Pujas',
    description: 'Chanting of the Sundarkand chapter from Ramayana on Hanuman\'s birthday, resolving mental blocks and building confidence.',
    shortDescription: 'Sundarkand reading on Hanuman Jayanti for confidence.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Sundarkand books', 'Boondi sweets', 'Jasmine oil', 'Sindoor', 'Red clothes', 'Fruits'],
    estimatedMaterialCost: 600,
    priceRange: { min: 2500, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['hanuman birthday', 'sundarkand path', 'ramayana reading', 'mental confidence', 'protection fear'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Laksha Deepotsava',
    slug: 'laksha-deepotsava',
    category: 'Festival Pujas',
    description: 'The festival of lighting one lakh oil lamps, commonly performed in temples across Karnataka (like Dharmasthala) during Karthika month to invite divine brightness.',
    shortDescription: 'Karnataka temple festival of lighting one lakh clay lamps.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Clay diyas (108 representative)', 'Oil barrels', 'Cotton wicks', 'Flowers', 'Camphor', 'Sweets'],
    estimatedMaterialCost: 3000,
    priceRange: { min: 5000, max: 15000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['light lamps', 'karnataka temple light', 'karthika deepotsava', 'dharmasthala lights', 'prosperity light'],
    occasionTags: ['Prosperity', 'Wealth'],
    supportedRegions: [],
    imageUrl: ''
  },

  // ── 7. Shiva Pujas (9) ──
  {
    pujaName: 'Rudrabhishek Puja',
    slug: 'rudrabhishek-puja',
    category: 'Shiva Pujas',
    description: 'A sacred bathing ritual of Shiva Lingam chanting Sri Rudram Vedic mantras. It bestows spiritual elevation, cleanses mind, and grants prosperity.',
    shortDescription: 'Sacred Shiva Lingam bathing with milk, honey, and bel leaves.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Shiva Lingam', 'Milk', 'Curd', 'Honey', 'Ghee', 'Sugar', 'Bel leaves', 'Sugarcane juice', 'Sandal paste'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3100, max: 7500 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['mahadev', 'shiva', 'rudra', 'abhishek', 'rudrabhishek', 'cleansing', 'peace of mind', 'health recovery'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Laghu Rudra Puja',
    slug: 'laghu-rudra-puja',
    category: 'Shiva Pujas',
    description: 'An advanced Shiva Puja involving 121 recitations of Sri Rudram and Havan, conducted by multiple pandits to resolve severe life issues and request recovery from illness.',
    shortDescription: 'Advanced 121 Rudram chanting and fire Havan by team of Pandits.',
    duration: '5 hours',
    durationMinutes: 300,
    requiredMaterials: ['11 Rudraksha malas', 'Large Havan kund', 'Huge quantities of ghee', 'Bel leaves (1008)', 'Fruits'],
    estimatedMaterialCost: 5000,
    priceRange: { min: 15000, max: 35000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['heavy shiva', 'multi pandit', 'rudram recitation', 'illness cure', 'special Havan'],
    occasionTags: ['Health', 'Protection'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Maha Rudra Puja',
    slug: 'maha-rudra-puja',
    category: 'Shiva Pujas',
    description: 'One of the ultimate rituals for Lord Shiva involving 1331 recitations of Rudram, bringing absolute protection and massive spiritual elevation to communities.',
    shortDescription: 'Grand community Shiva worship with 1331 Rudram chants.',
    duration: '8 hours',
    durationMinutes: 480,
    requiredMaterials: ['Massive havan kund', 'Special herbs', '11 Pandits team', 'Dhoti clothes', 'Panchamrit barrels'],
    estimatedMaterialCost: 15000,
    priceRange: { min: 51000, max: 125000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['ultimate shiva', 'yajna', '11 pandits', 'community blessing', 'protection country', 'huge fire'],
    occasionTags: ['Protection', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Shiva Sahasranama Archana',
    slug: 'shiva-sahasranama-archana',
    category: 'Shiva Pujas',
    description: 'Chanting of 1000 names of Lord Shiva while offering flowers or bel leaves on the Shiva Lingam, bringing focus, wisdom, and peace.',
    shortDescription: 'Offering flowers while reciting 1000 names of Lord Shiva.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Bel leaves (1000)', 'Flowers', 'Shiva Lingam', 'Sandalwood paste', 'Incense', 'Sweets'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['1000 shiva names', 'archana', 'bel path', 'focus boost', 'education mind', 'peace'],
    occasionTags: ['Education', 'Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Somvar Vrat Udyapan',
    slug: 'somvar-vrat-udyapan',
    category: 'Shiva Pujas',
    description: 'The formal completion puja of Solah Somvar (16 Mondays) fasts. Couples or singles perform it to find a desired life partner or request family wellness.',
    shortDescription: 'Closing ceremony of 16 Mondays fasts of Lord Shiva.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['White cloth', 'Churma prasad', 'White flowers', 'Janeu', 'Shiva Parvati idol', 'Coconut'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['solah somvar', '16 mondays', 'find husband', 'vrat end', 'marriage blessing', 'wellness'],
    occasionTags: ['Marriage', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Pradosh Vrat Puja',
    slug: 'pradosh-vrat-puja',
    category: 'Shiva Pujas',
    description: 'Performed during twilight on Trayodashi (13th lunar day) to cleanse negative patterns and build mental peace.',
    shortDescription: 'Twilight Shiva prayers on 13th lunar day for mental peace.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Lord Shiva photo', 'Bhilva leaves', 'Milk', 'Honey', 'Camphor', 'Sesame oil lamp'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['trayodashi', 'twilight prayer', 'karmic clearing', 'pradosham', 'mental health', 'peace'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Kedarnath Gauri Shankar Archana',
    slug: 'kedarnath-gauri-shankar-archana',
    category: 'Shiva Pujas',
    description: 'Worshiping Lord Shiva and Gauri, drawing energy patterns from Kedarnath shrines, for removing bad luck and requesting marriage compatibility.',
    shortDescription: 'Shiva-Gauri archana invoking Kedarnath energies.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Kedarnath photo', 'Red and white threads', 'Sweets', 'Panchamrit', 'Bel leaves', 'Lotus'],
    estimatedMaterialCost: 700,
    priceRange: { min: 2200, max: 4800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kedarnath', 'gauri shankar', 'marriage compatibility', 'early marriage', 'couple union'],
    occasionTags: ['Marriage', 'Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Bilvapatra Archana',
    slug: 'bilvapatra-archana',
    category: 'Shiva Pujas',
    description: 'A continuous offering of three-leaf bilvapatra (Bel leaves) to Shiva, symbolizing the three attributes (Sattva, Rajas, Tamas) to gain focus.',
    shortDescription: 'Continuous Bel leaf offerings on Shiva Lingam for focus.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Fresh green Bel leaves (108)', 'Sandalwood paste', 'Shiva Lingam', 'Incense', 'Ghee lamp'],
    estimatedMaterialCost: 300,
    priceRange: { min: 1200, max: 2800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['bel leaves', 'three leaf', 'self realization', 'simple shiva', 'focus mind', 'intellect'],
    occasionTags: ['Education', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Karthika Somavara Abhisheka',
    slug: 'karthika-somavara-abhisheka',
    category: 'Shiva Pujas',
    description: 'Performed on Mondays of the holy Karthika month in Karnataka. Bathing Shiva Lingam with water and milk to request health and ancestral peace.',
    shortDescription: 'Karthika month Monday special milk bath of Shiva Lingam.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Bel leaves', 'Milk (5 liters)', 'Honey', 'Curd', 'Panchamrit', 'Rice for offering', 'Flowers'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['karthika somavara', 'monday shiva', 'milk bath', 'karnataka shiva puja', 'ancestor peace'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },

  // ── 8. Vishnu Pujas (9) ──
  {
    pujaName: 'Vishnu Sahasranama Path',
    slug: 'vishnu-sahasranama-path',
    category: 'Vishnu Pujas',
    description: 'Chanting of the 1000 names of Lord Maha Vishnu. Highly effective for reducing mental stress and request peaceful family flow.',
    shortDescription: 'Devotional chanting of the 1000 names of Lord Vishnu.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Vishnu photo', 'Tulsi leaves', 'Yellow flowers', 'Sweets', 'Camphor', 'Sandalwood paste'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['1000 vishnu names', 'tulsi offering', 'stress relief', 'anxiety relief', 'shanti', 'peace', 'prosperity'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Shaligram Puja',
    slug: 'shaligram-puja',
    category: 'Vishnu Pujas',
    description: 'Bathing and worshiping the sacred Shaligram stone (representing Vishnu) with Tulsi water, bringing righteousness and peace to the house.',
    shortDescription: 'Holy Shaligram stone worship using fresh Tulsi water.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Shaligram stone', 'Tulsi leaves', 'Milk', 'Conch shell', 'Yellow silk cloth', 'Sandalwood'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['shaligram', 'conch shell', 'righteousness', 'tulsi water', 'home peace', 'ancestor clean'],
    occasionTags: ['Prosperity', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Purushottam Maas Puja',
    slug: 'purushottam-maas-puja',
    category: 'Vishnu Pujas',
    description: 'Conducted during the leap month (Adhik Maas) dedicated to Lord Purushottam (Vishnu). Amplifies the benefits of charity, prayers, and cleanses deep karmas.',
    shortDescription: 'Leap month special devotional prayers to Lord Vishnu.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Adhik maas book', 'Deep (lamps) 33 numbers', 'Malpua sweets', 'Yellow clothes', 'Tulsi'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3500, max: 7500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['adhik maas', 'leap month', 'purushottam', 'karma cleanse', 'malpua bhog', 'charity', 'prosperity'],
    occasionTags: ['Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Anant Chaturdashi Puja',
    slug: 'anant-chaturdashi-puja',
    category: 'Vishnu Pujas',
    description: 'Worshiping Lord Ananta (the infinite form of Vishnu) and tying a sacred 14-knot thread on the arm to request protection and recovery of lost fortune.',
    shortDescription: 'Worship of Infinite Vishnu and tying 14-knot thread.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Anant thread (14 knots)', '14 wheat flour purls', 'Vishnu photo', 'Flowers', 'Panchamrit'],
    estimatedMaterialCost: 800,
    priceRange: { min: 2200, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['ananta thread', 'infinite protection', '14 knots', 'lost fortune', 'chaturdashi', 'recovery'],
    occasionTags: ['Protection', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Rama Raksha Stotra Path',
    slug: 'rama-raksha-stotra-path',
    category: 'Vishnu Pujas',
    description: 'A powerful prayer composed by Saint Budha Kaushika, seeking the defensive shielding of Lord Rama to fight off fears and obstacles.',
    shortDescription: 'Defensive chanting of Rama Raksha Stotra for courage.',
    duration: '1.5 hours',
    durationMinutes: 90,
    requiredMaterials: ['Rama family photo', 'Red thread', 'Rice grains', 'Betel leaves', 'Laddoo sweets'],
    estimatedMaterialCost: 500,
    priceRange: { min: 1500, max: 3200 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['rama protection', 'stotra path', 'court issue', 'fear removal', 'shielding', 'courage'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Gita Path Puja',
    slug: 'gita-path-puja',
    category: 'Vishnu Pujas',
    description: 'Reading of selected chapters of Bhagavad Gita, invoking Lord Krishna to clear mental confusion and grant spiritual discrimination.',
    shortDescription: 'Bhagavad Gita reading for mental clarity and career direction.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Bhagavad Gita book', 'Yellow flower garland', 'Incense', 'Ghee lamp', 'Sweets'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1800, max: 3800 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['bhagavad gita', 'krishna guidance', 'discrimination', 'clear confusion', 'career focus', 'education clarity'],
    occasionTags: ['Education', 'Career Growth'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Venkateshwara Swamy Puja',
    slug: 'venkateshwara-swamy-puja',
    category: 'Vishnu Pujas',
    description: 'Dedicated to Lord Venkateshwara of Tirupati, performed with detailed floral offerings and chanting to request wealth, career success, and financial abundance.',
    shortDescription: 'Devotional worship of Lord Balaji for wealth and career growth.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Balaji photo/idol', 'Lotus flowers', 'Tulsi leaves', 'Laddoo sweets', 'Saffron', 'Camphor'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3000, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['balaji puja', 'venkateshwara karnataka', 'tirupati lord', 'wealth creation', 'career growth', 'financial success'],
    occasionTags: ['Prosperity', 'Wealth', 'Career Growth'],
    supportedRegions: ['Karnataka', 'Andhra Pradesh', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Gajendra Moksha Path',
    slug: 'gajendra-moksha-path',
    category: 'Vishnu Pujas',
    description: 'Recitation of the chapter from Srimad Bhagavatam where Vishnu saves Gajendra (elephant) from a crocodile, performed to request financial recovery and debt relief.',
    shortDescription: 'Bhagavatam recitation for debt relief and financial help.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Vishnu flying on Garuda photo', 'Tulsi', 'Yellow flowers', 'Curd', 'Panchamrit'],
    estimatedMaterialCost: 600,
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['debt trap', 'financial crisis', 'gajendra', 'crocodile escape', 'heavy relief', 'wealth recovery'],
    occasionTags: ['Prosperity', 'Wealth'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Srinivasa Kalyana',
    slug: 'srinivasa-kalyana',
    category: 'Vishnu Pujas',
    description: 'The ceremonial wedding of Lord Srinivasa (Venkateshwara) with Padmavathi Devi, bringing marital harmony and financial abundance to the performing family.',
    shortDescription: 'Marriage ceremony of Lord Venkateshwara for wealth and marital bliss.',
    duration: '4 hours',
    durationMinutes: 240,
    requiredMaterials: ['Balaji Padmavathi idols', 'Sringaar accessories', 'Garlands (4)', 'Sugarcane stalks', 'Fruits & sweets', 'Kalash'],
    estimatedMaterialCost: 3000,
    priceRange: { min: 5500, max: 12000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['lord balaji wedding', 'srinivasa kalyana', 'marital harmony', 'family wealth', 'tirupati kalyanam'],
    occasionTags: ['Marriage', 'Wealth', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Andhra Pradesh'],
    imageUrl: ''
  },

  // ── 9. Devi Pujas (9) ──
  {
    pujaName: 'Chandi Path (Durga Saptashati)',
    slug: 'chandi-path-durga-saptashati',
    category: 'Devi Pujas',
    description: 'Reading of the 700 verses of Durga Saptashati, powerful for overcoming obstacles, protection from disputes, and obtaining reputation.',
    shortDescription: 'Recitation of 700 verses of Durga Saptashati for protection.',
    duration: '4.5 hours',
    durationMinutes: 270,
    requiredMaterials: ['Saptashati book', 'Durga photo', 'Sringaar kit', 'Red flowers', 'Ghee', 'Panchamrit', 'Lemon garland'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 5100, max: 12000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['durga path', 'saptashati', 'chandi', 'obstacle removal', 'court success', 'protection', 'reputation boost'],
    occasionTags: ['Protection', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Saraswati Puja for Knowledge',
    slug: 'saraswati-puja-for-knowledge',
    category: 'Devi Pujas',
    description: 'Conducted on Vasant Panchami or general days to request memory power, musical skills, artistic abilities, and deep academic wisdom.',
    shortDescription: 'Devotional prayers to Goddess Saraswati for education and arts.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['White flowers', 'Yellow rice', 'Pens/Notebooks', 'Saraswati photo', 'Sweets (Boondi)'],
    estimatedMaterialCost: 600,
    priceRange: { min: 1800, max: 3500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['vasant panchami', 'artistic skills', 'music blessing', 'saraswati devi', 'education', 'exam blessing', 'children study'],
    occasionTags: ['Education'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Varalakshmi Vrat Puja',
    slug: 'varalakshmi-vrat-puja',
    category: 'Devi Pujas',
    description: 'Household format of Varamahalakshmi Vrata performed by married women on Shravana Friday, praying for the family\'s safety, health and wealth.',
    shortDescription: 'Shravana Friday household Lakshmi worship for marital bliss.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Lakshmi face mask', 'Kalash pot', 'Nine-knot thread', 'Sringaar items', 'Coconut', 'Gold coins'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['shravan friday', 'south india puja', 'married women luck', 'varalakshmi', 'gold worship', 'wealth', 'prosperity'],
    occasionTags: ['Prosperity', 'Wealth', 'Marriage'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Lalita Sahasranama Archana',
    slug: 'lalita-sahasranama-archana',
    category: 'Devi Pujas',
    description: 'Chanting of 1000 names of Lalita Tripura Sundari, invoking ultimate grace, health, and family wellness.',
    shortDescription: 'Kumkum archana with 1000 names of Goddess Lalita.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Kumkum (red powder)', 'Red roses (1000)', 'Devi photo', 'Lotus', 'Ghee lamp', 'Sweets'],
    estimatedMaterialCost: 650,
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kumkum archana', 'lalita devi', 'tripura sundari', 'grace', '1000 devi names', 'family wellness'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Gayatri Mantra Jaap',
    slug: 'gayatri-mantra-jaap',
    category: 'Devi Pujas',
    description: 'Chanting of the sacred Gayatri Mantra (up to 10,000 times) to purify intellect, request wisdom, and increase aura brightness.',
    shortDescription: 'Purification Gayatri chanting for intellect and wisdom.',
    duration: '3.5 hours',
    durationMinutes: 210,
    requiredMaterials: ['Yellow cloth seat', 'Tulsi/Sandalwood mala', 'Gangajal', 'Camphor', 'Ghee lamp'],
    estimatedMaterialCost: 500,
    priceRange: { min: 3100, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['gayatri devi', 'mantra jaap', 'aura clean', 'intellect boost', 'education', 'wisdom'],
    occasionTags: ['Education', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Kali Puja for Negativity Removal',
    slug: 'kali-puja-for-negativity-removal',
    category: 'Devi Pujas',
    description: 'Dedicated to Goddess Maha Kali, removing negative entities, fear of darkness, and heavy mental anxiety.',
    shortDescription: 'Goddess Kali worship to remove fear and negative forces.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Hibiscus flowers (red)', 'Lemon garland', 'Black sesame', 'Kali photo', 'Camphor', 'Mustard seeds'],
    estimatedMaterialCost: 800,
    priceRange: { min: 3500, max: 8000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kali maa', 'darkness fear', 'anxiety cure', 'entities removal', 'protection', 'fear relief'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Santoshi Maa Vrat Udyapan',
    slug: 'santoshi-maa-vrat-udyapan',
    category: 'Devi Pujas',
    description: 'The closing ritual of 16 Fridays fast of Santoshi Maa, bringing peace and satisfaction, resolving family arguments.',
    shortDescription: 'Closing ceremony of 16 Fridays fast of Santoshi Maa.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Chickpeas and Jaggery (Chana-Gur)', 'Santoshi Maa photo', 'Sour foods prohibited', 'Sweets for children'],
    estimatedMaterialCost: 600,
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['16 fridays', 'chana gur', 'satisfaction goddess', 'vrat end', 'family peace', 'harmony'],
    occasionTags: ['Prosperity', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Radha Krishna Yugal Puja',
    slug: 'radha-krishna-yugal-puja',
    category: 'Devi Pujas',
    description: 'Worship of the divine couple Radha and Krishna to cultivate unconditional love, empathy, and smooth out marital conflicts.',
    shortDescription: 'Worship of Radha & Krishna for love and family harmony.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Radha Krishna photo', 'Flute', 'Peacock feathers', 'Tulsi', 'Yellow garments', 'Butter bhog'],
    estimatedMaterialCost: 700,
    priceRange: { min: 2000, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['love couple', 'family dispute', 'krishna radha', 'unconditional love', 'marriage happiness', 'harmony'],
    occasionTags: ['Marriage', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Durga Homa',
    slug: 'durga-homa',
    category: 'Devi Pujas',
    description: 'A powerful fire ritual dedicated to Goddess Durga, performed in Karnataka to clear negative entities, remove fear, and protect the family from accidents.',
    shortDescription: 'Goddess Durga fire ritual for family safety and protection.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Havan kund', 'Durga photo', 'Sringaar kit', 'Red flowers', 'Herbal havan powder', 'Ghee', 'Coconuts'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 4000, max: 8500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['durga fire', 'protection havan', 'remove fear', 'karnataka durga', 'safety', 'accident prevent'],
    occasionTags: ['Protection', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },

  // ── 10. Homa & Havan Rituals (12) ──
  {
    pujaName: 'Ganapathi Homa',
    slug: 'ganapathi-homa',
    category: 'Homa & Havan Rituals',
    description: 'A sacred fire ritual dedicated to Lord Ganesha, typically performed early morning in Karnataka homes or offices to remove obstacles and assure prosperity.',
    shortDescription: 'Auspicious morning Ganesha fire ceremony to clear obstacles.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Havan Kund', 'Ganesha idol', 'Modak sweets', 'Desi Ghee', 'Havan samagri pack', 'Dry coconut', 'Red flowers'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3000, max: 6500 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['ganesha havan', 'morning homa', 'obstacle free', 'ganapathi homa', 'karnataka homa', 'new business', 'new home'],
    occasionTags: ['New Home', 'Business Opening', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Chandi Homa',
    slug: 'chandi-homa',
    category: 'Homa & Havan Rituals',
    description: 'A grand fire ritual dedicated to Goddess Chandi. Invokes ultimate divine feminine energy to remove severe professional blocks, resolve court matters, and grant massive success.',
    shortDescription: 'Grand fire ritual of Goddess Chandi for victory and career growth.',
    duration: '6 hours',
    durationMinutes: 360,
    requiredMaterials: ['Large Havan Kund', 'Dhoti garments', 'Lotus flowers', 'Dry coconut halves', 'Fruits', 'Special herbs mix', 'Red cloth'],
    estimatedMaterialCost: 6000,
    priceRange: { min: 18000, max: 45000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['chandi havan', 'heavy fire ritual', 'career barrier', 'durga fire', 'fortune', 'victory', 'court win'],
    occasionTags: ['Protection', 'Career Growth', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Ayushya Homa',
    slug: 'ayushya-homa',
    category: 'Homa & Havan Rituals',
    description: 'Conducted in Karnataka on birthdays (especially 1st birthdays or of seniors) to seek Ayur Devata blessings for longevity, health, and vitality.',
    shortDescription: 'Longevity and good health birthday fire ritual.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Havan Samagri', 'Ayushya herbs', 'Pure ghee', 'Yellow rice', 'Durva grass', 'Fruits & sweets'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3500, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['birthday homa', 'longevity', 'vitality', 'ayushya', 'elderly health', 'karnataka homa', 'baby first birthday'],
    occasionTags: ['Child Birth', 'Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Sudarshana Homa',
    slug: 'sudarshana-homa',
    category: 'Homa & Havan Rituals',
    description: 'A powerful fire ritual dedicated to Lord Sudarshana (Vishnu\'s weapon disc) to purge negative vibrations, resolve professional jealousy, and shield the family.',
    shortDescription: 'Vishnu weapon disc fire ceremony for family protection.',
    duration: '4 hours',
    durationMinutes: 240,
    requiredMaterials: ['Sudarshana Yantra', 'Red roses', 'Havan herbs', 'Ghee', 'Pineapple fruits', 'Camphor', 'Wood'],
    estimatedMaterialCost: 2500,
    priceRange: { min: 5000, max: 11000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['enemy removal', 'jealousy clearing', 'weapon disc', 'sudarshana chakra', 'heavy havan', 'protection', 'business guard'],
    occasionTags: ['Protection', 'Career Growth', 'Business Opening'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Mrityunjaya Homa',
    slug: 'mrityunjaya-homa',
    category: 'Homa & Havan Rituals',
    description: 'Fire ritual format of Maha Mrityunjaya, offering black sesame seeds and specialized herbs to the fire, performed in Karnataka to cure critical illness and protect life.',
    shortDescription: 'Life-protecting fire ritual for recovery from critical illness.',
    duration: '4 hours',
    durationMinutes: 240,
    requiredMaterials: ['Rudraksha beads', 'Black sesame', 'Durva grass', 'Giloy herbs', 'Ghee', 'Wood', 'Camphor'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 5500, max: 12000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['critical illness fire', 'shiva fire', 'mrityunjaya havan', 'save life', 'health recovery', 'protection', 'karnataka homa'],
    occasionTags: ['Health', 'Protection'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Saraswati Homa',
    slug: 'saraswati-homa',
    category: 'Homa & Havan Rituals',
    description: 'Fire ritual dedicated to Goddess Saraswati, helping students preparing for tough exams to clear memory blocks and raise mental clarity.',
    shortDescription: 'Education and academic focus fire ceremony.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['White flowers', 'Lotus seeds', 'Ghee', 'Sweet rice prasad', 'Yellow fruits', 'Notebook for blessing'],
    estimatedMaterialCost: 1200,
    priceRange: { min: 3000, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['education fire', 'exam boost havan', 'saraswati havan', 'memory fire', 'passing tests', 'school start'],
    occasionTags: ['Education'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Lakshmi Narayana Homa',
    slug: 'lakshmi-narayana-homa',
    category: 'Homa & Havan Rituals',
    description: 'A grand fire ritual in Karnataka honoring Lord Narayana and Goddess Lakshmi, performed to bless families with material wealth and marital happiness.',
    shortDescription: 'Worship of Lakshmi and Vishnu for marital joy and wealth.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Lakshmi Narayana photo', 'Lotus flowers', 'Honey', 'Yellow cloth', 'Ghee', 'Coconuts', 'Sweets'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 4500, max: 9000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['wealth homa', 'family wealth', 'marriage harmony', 'lakshmi narayana', 'karnataka homa', 'prosperity', 'wealth'],
    occasionTags: ['Prosperity', 'Wealth', 'Marriage'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Rudra Homa',
    slug: 'rudra-homa',
    category: 'Homa & Havan Rituals',
    description: 'Sacred fire ritual to pacify Lord Rudra, washing off deep errors and request wellness and positive planetary vibrations.',
    shortDescription: 'Lord Shiva Rudra fire ceremony for general wellness.',
    duration: '3.5 hours',
    durationMinutes: 210,
    requiredMaterials: ['Bel leaves', 'Black sesame', 'Ghee', 'Rudra samagri pack', 'White sweets', 'Coconut halves'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 4500, max: 9000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['rudra havan', 'ancestral curse', 'shiva fire homa', 'wellness', 'protection'],
    occasionTags: ['Health', 'Protection'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Karika Dahan Havan',
    slug: 'karika-dahan-havan',
    category: 'Homa & Havan Rituals',
    description: 'Performed on special Saturdays to request relief from debt liabilities, offering black sesame seeds and cotton seeds to the fire.',
    shortDescription: 'Saturday special fire offering for debt clearing.',
    duration: '2 hours',
    durationMinutes: 120,
    requiredMaterials: ['Black sesame', 'Cotton seeds', 'Crude wood', 'Camphor', 'Mustard oil lamp'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['debt burn', 'saturday fire', 'sesame offering', 'financial relief', 'wealth recovery'],
    occasionTags: ['Prosperity', 'Wealth'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Satyanarayana Homa',
    slug: 'satyanarayana-homa',
    category: 'Homa & Havan Rituals',
    description: 'The fire ritual format of the Satyanarayana Vrata, performed extensively in Karnataka to seal prayers with a holy fire offering for quick results.',
    shortDescription: 'Satyanarayana worship coupled with a holy fire Homa.',
    duration: '3.5 hours',
    durationMinutes: 210,
    requiredMaterials: ['Wheat rava prasad', 'Havan wood', 'Lotus flowers', 'Satyanarayana Yantra', 'Ghee', 'Banana trunks'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 4500, max: 8500 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['satyanarayan homa', 'vishnu fire', 'karnataka Homa', 'family prosperity', 'quick results'],
    occasionTags: ['Prosperity', 'Health'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Navadhanya Homa',
    slug: 'navadhanya-homa',
    category: 'Homa & Havan Rituals',
    description: 'A special homa using nine grains (Navadhanya) offered to the fire to seek generic environmental support, food abundance, and agricultural success.',
    shortDescription: 'Grains offering fire ritual for food and crop abundance.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Nine grains (Navadhanya)', 'Pure ghee', 'Havan samagri', 'Dry coconuts', 'Yellow flowers'],
    estimatedMaterialCost: 1500,
    priceRange: { min: 3000, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['grains fire', 'agricultural success', 'food abundance', 'sankranti homa', 'prosperity'],
    occasionTags: ['Prosperity'],
    supportedRegions: [],
    imageUrl: ''
  },
  {
    pujaName: 'Shatru Samhara Homa',
    slug: 'shatru-samhara-homa',
    category: 'Homa & Havan Rituals',
    description: 'Dedicated to Lord Kartikeya (Subrahmanya), performed in temples or homes to remove corporate jealousy, litigation fears, and protect properties.',
    shortDescription: 'Kartikeya fire ritual for protection from litigation and rivalry.',
    duration: '3 hours',
    durationMinutes: 180,
    requiredMaterials: ['Red flowers', 'Subrahmanya photo', 'Mustard seeds', 'Ghee', 'Lemon garland', 'Havan wood'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 4500, max: 9500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['litigation escape', 'kartikeya fire', 'rivalry clearing', 'protection', 'property guard'],
    occasionTags: ['Protection', 'Career Growth'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },

  // ── 11. Special Vedic Ceremonies (8) ──
  {
    pujaName: 'Pitra Dosh Nivaran Puja',
    slug: 'pitra-dosh-nivaran-puja',
    category: 'Special Vedic Ceremonies',
    description: 'Conducted at holy sites (like Gaya, Rameshwaram, or locally) to satisfy ancestors who passed away with unfulfilled desires, restoring family expansion and peace.',
    shortDescription: 'Ancestral peace ritual to clear family growth blocks.',
    duration: '3.5 hours',
    durationMinutes: 210,
    requiredMaterials: ['Rice flour balls (Pindas)', 'Black sesame', 'Kusha grass', 'White flowers', 'Gangajal', 'Honey', 'White dhoti clothes'],
    estimatedMaterialCost: 2000,
    priceRange: { min: 4100, max: 9500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['ancestor peace', 'gaya puja', 'pitru dosh', 'family block', 'pinda daan', 'peace', 'family harmony'],
    occasionTags: ['Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Narayan Bali Puja',
    slug: 'narayan-bali-puja',
    category: 'Special Vedic Ceremonies',
    description: 'A highly specialized ritual for ancestors who met with unnatural ends, releasing their souls and protecting descendants from family blocks.',
    shortDescription: 'Soul release ritual for ancestors who passed away in accidents.',
    duration: '4.5 hours',
    durationMinutes: 270,
    requiredMaterials: ['Gold dummy body representative', 'Dharba grass', 'Large havan kit', 'Rice flour balls', 'Flowers', 'Panchamrit'],
    estimatedMaterialCost: 3500,
    priceRange: { min: 6500, max: 15000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['accidental death', 'unnatural death', 'soul release', 'narayan bali', 'heavy ancestor', 'protection'],
    occasionTags: ['Protection', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  },
  {
    pujaName: 'Shasti Poorthi (60th Birthday)',
    slug: 'shasti-poorthi-60th-birthday',
    category: 'Special Vedic Ceremonies',
    description: 'A grand ceremony celebrated when a person completes 60 years. Involves renewing wedding vows and executing major Abhishek/Havan for physical health.',
    shortDescription: '60th birthday celebration with wedding vow renewals and abhishek.',
    duration: '4.5 hours',
    durationMinutes: 270,
    requiredMaterials: ['11 Kalash pots', 'Wedding garlands', 'New couple clothes', 'Havan wood', 'Makhana sweets', 'Red threads'],
    estimatedMaterialCost: 4000,
    priceRange: { min: 8500, max: 20000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['60th birthday', 'vow renewal', 'elderly health', 'shastipoorthi', 'abhishek', 'good health', 'longevity'],
    occasionTags: ['Health', 'Marriage', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Sathabhishekam (80th Birthday)',
    slug: 'sathabhishekam-80th-birthday',
    category: 'Special Vedic Ceremonies',
    description: 'Celebrated when a person sees 1000 full moons (around 80 years and 8 months of age), seeking high blessings for longevity and family health.',
    shortDescription: '80th birthday ceremony honoring life of 1000 full moons.',
    duration: '4.5 hours',
    durationMinutes: 270,
    requiredMaterials: ['Gold flowers representation', '1000 moon representation pots', 'New clothes', 'Garlands', 'Abhishek items'],
    estimatedMaterialCost: 5000,
    priceRange: { min: 11000, max: 25000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['80th birthday', '1000 moons', 'sathabhishekam', 'longevity blessing', 'good health'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Bheema Ratha Shanthi (70th Birthday)',
    slug: 'bheema-ratha-shanthi-70th-birthday',
    category: 'Special Vedic Ceremonies',
    description: 'Celebrated at the completion of 70 years, seeking Mrityunjaya blessings and family unity.',
    shortDescription: '70th birthday family blessings for health and longevity.',
    duration: '4 hours',
    durationMinutes: 240,
    requiredMaterials: ['Abhishek pots', 'Garlands', 'New garments', 'Ghee', 'Fruits', 'Vedic text books'],
    estimatedMaterialCost: 3000,
    priceRange: { min: 7500, max: 18000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['70th birthday', 'bheema ratha', 'mrityunjaya blessing', 'good health', 'longevity'],
    occasionTags: ['Health', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu'],
    imageUrl: ''
  },
  {
    pujaName: 'Shat Chandi Yajna',
    slug: 'shat-chandi-yajna',
    category: 'Special Vedic Ceremonies',
    description: 'An extremely powerful, multi-day royal ritual where Chandi Path is chanted 100 times by 5 or more Pandits to bring victory, massive wealth, and public fame.',
    shortDescription: 'Royal 3-day fire Yajna chanting Chandi Path 100 times.',
    duration: '15 hours (3 days)',
    durationMinutes: 900,
    requiredMaterials: ['Grand Havan Kund', 'Team of 5 Pandits', 'Piles of wood', 'Ghee liters', 'Sringaar sets (10)', 'Huge prasads'],
    estimatedMaterialCost: 25000,
    priceRange: { min: 75000, max: 200000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['shatchandi', 'royal yajna', '3 days ritual', 'public fame', '5 pandits', 'victory', 'wealth'],
    occasionTags: ['Prosperity', 'Wealth', 'Protection'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Atirudra Maha Yajna',
    slug: 'atirudra-maha-yajna',
    category: 'Special Vedic Ceremonies',
    description: 'The ultimate fire ritual for Lord Shiva where Sri Rudram is chanted 14,641 times by a team of 111 Pandits, bringing absolute positive energy to earth.',
    shortDescription: '11-day ultimate Shiva Yajna with 111 Pandits team.',
    duration: '30 hours (11 days)',
    durationMinutes: 1800,
    requiredMaterials: ['Massive temple-sized havan', '111 Pandits team', 'Barrels of ghee', 'Tons of woods', 'Food for community'],
    estimatedMaterialCost: 100000,
    priceRange: { min: 250000, max: 750000 },
    locationType: 'Temple',
    featured: false,
    popular: false,
    searchKeywords: ['atirudra', '11 days yajna', '111 pandits', 'ultimate positive energy', 'protection', 'shiva fire'],
    occasionTags: ['Protection', 'Prosperity'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    imageUrl: ''
  },
  {
    pujaName: 'Shanti Karan Yajna',
    slug: 'shanti-karan-yajna',
    category: 'Special Vedic Ceremonies',
    description: 'Vedic ceremony performed to pacify planetary anomalies or home conflicts, establishing complete peace and wellness.',
    shortDescription: 'Vedic peace fire Yajna for home conflict resolution.',
    duration: '2.5 hours',
    durationMinutes: 150,
    requiredMaterials: ['Havan wood', 'Samagri', 'Ghee', 'Panchamrit', 'White flowers', 'Sandal paste'],
    estimatedMaterialCost: 1000,
    priceRange: { min: 3000, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['home conflicts', 'peace yajna', 'shanti karan', 'family peace', 'harmony'],
    occasionTags: ['Prosperity', 'Health'],
    supportedRegions: ['Karnataka', 'Tamil Nadu', 'Maharashtra'],
    imageUrl: ''
  }
];

module.exports = ritualsData;
