const ritualsData = [
  // ── 1. Griha & Property Pujas (9) ──
  {
    pujaName: 'Griha Pravesh Puja',
    slug: 'griha-pravesh-puja',
    category: 'Griha & Property Pujas',
    description: 'A comprehensive housewarming ceremony performed before moving into a new home. It purifies the living space, dispels negative energy, and seeks blessings from deities for happiness and prosperity.',
    duration: '3-4 hours',
    requiredMaterials: ['Kalash', 'Mango leaves', 'Coconut', 'Kumkum', 'Turmeric', 'Rice', 'Ghee', 'Havan Samagri', 'Flowers', 'Panchamrit'],
    priceRange: { min: 3500, max: 8500 },
    locationType: 'Home',
    featured: true,
    popular: true,
    searchKeywords: ['housewarming', 'new home', 'home entry', 'vastu', 'graha pravesh', 'grihapravesh']
  },
  {
    pujaName: 'Bhumi Puja',
    slug: 'bhumi-puja',
    category: 'Griha & Property Pujas',
    description: 'Performed before starting construction on a piece of land to seek permission and blessings from Mother Earth (Bhumi Devi) and Vaastu Purush.',
    duration: '2-3 hours',
    requiredMaterials: ['Bricks', 'Coconut', 'Flowers', 'Betel leaves', 'Navadhanya (9 grains)', 'Ghee', 'Turmeric', 'Kumkum'],
    priceRange: { min: 3100, max: 6500 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['land purchase', 'construction', 'plot puja', 'foundation', 'bhumi devi']
  },
  {
    pujaName: 'Vastu Shanti Puja',
    slug: 'vastu-shanti-puja',
    category: 'Griha & Property Pujas',
    description: 'Conducted to rectify any architectural or structural defects (Vastu Doshas) in a home or commercial property, bringing harmony, health, and peace.',
    duration: '3-4 hours',
    requiredMaterials: ['Vastu Yantra', 'Havan Kund', 'Wood', 'Ghee', 'Flowers', 'Sweets', 'Panchamrit', 'Gangajal'],
    priceRange: { min: 4000, max: 9000 },
    locationType: 'Home',
    featured: true,
    popular: false,
    searchKeywords: ['vastu dosh', 'home peace', 'architectural defect', 'vastu shanti', 'harmony']
  },
  {
    pujaName: 'Office Puja / Business Inauguration',
    slug: 'office-puja-business-inauguration',
    category: 'Griha & Property Pujas',
    description: 'An auspicious ritual performed before starting a new business, opening a shop, or moving into a new office space to invoke success, growth, and wealth.',
    duration: '2-3 hours',
    requiredMaterials: ['Ganesh idol', 'Lakshmi photo', 'Red thread', 'Flowers', 'Sweets', 'Coconut', 'Incense', 'Camphor'],
    priceRange: { min: 2500, max: 7000 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['new office', 'shop opening', 'inauguration', 'business startup', 'workplace']
  },
  {
    pujaName: 'Dwar Puja',
    slug: 'dwar-puja',
    category: 'Griha & Property Pujas',
    description: 'Performed at the main entrance door of a newly rented or bought house to prevent evil spirits or negative vibes from entering the premises.',
    duration: '1-1.5 hours',
    requiredMaterials: ['Mango leaves garland', 'Kumkum', 'Turmeric', 'Coconut', 'Flowers', 'Oil lamp'],
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['door entry', 'entrance puja', 'protection', 'threshold']
  },
  {
    pujaName: 'Shila Nyas Puja',
    slug: 'shila-nyas-puja',
    category: 'Griha & Property Pujas',
    description: 'The formal foundation stone-laying ceremony for large structures, temples, or residential complexes, seeking divine support for completion without obstacles.',
    duration: '2.5-3.5 hours',
    requiredMaterials: ['Foundation stone', 'Five metals (Panchadhatu)', 'Navadhanya', 'Sandalwood paste', 'Flowers'],
    priceRange: { min: 5000, max: 12000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['foundation stone', 'construction start', 'stone laying', 'masonry']
  },
  {
    pujaName: 'Boring / Water Well Puja',
    slug: 'boring-water-well-puja',
    category: 'Griha & Property Pujas',
    description: 'Ritual performed to bless the earth before boring for groundwater or digging a well, praying for abundance of clean water and safety of the workers.',
    duration: '1-2 hours',
    requiredMaterials: ['Coconut', 'Flowers', 'Camphor', 'Betel nuts', 'Saffron', 'Rice grains'],
    priceRange: { min: 1800, max: 3500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['water boring', 'tube well', 'well digging', 'groundwater']
  },
  {
    pujaName: 'Vastu Purush Homam',
    slug: 'vastu-purush-homam',
    category: 'Griha & Property Pujas',
    description: 'Dedicated specifically to Vastu Purush (the deity of building sites) to correct energy flows and pacify negative planetary alignments influencing the property.',
    duration: '3 hours',
    requiredMaterials: ['Havan Samagri', 'Ghee', 'Vastu Purush idol', 'Special herbs', 'Flowers', 'Panchamrit'],
    priceRange: { min: 4500, max: 8000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['energy correction', 'vastu homa', 'building energy', 'house peace']
  },
  {
    pujaName: 'Property Sale Puja',
    slug: 'property-sale-puja',
    category: 'Griha & Property Pujas',
    description: 'A special prayer performed to remove obstacles in selling a plot, building, or house, invoking Vyasa and Lord Ganesha to attract suitable buyers.',
    duration: '1.5-2.5 hours',
    requiredMaterials: ['Clay lamp', 'Rice', 'Flowers', 'Sandalwood', 'Turmeric', 'Coconut', 'Yellow cloth'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['selling property', 'real estate sale', 'remove obstacles', 'buyer attraction']
  },

  // ── 2. Marriage & Family Rituals (9) ──
  {
    pujaName: 'Vivah (Vedic Wedding)',
    slug: 'vivah-vedic-wedding',
    category: 'Marriage & Family Rituals',
    description: 'A traditional and complete Vedic Hindu marriage ceremony comprising the Saptapadi (seven steps), Kanyadaan, Mangalsutra dharana, and Panigrahana.',
    duration: '4-6 hours',
    requiredMaterials: ['Mandap decor', 'Havan Kund', 'Garlands', 'Mangalsutra', 'Sindoor', 'Rice', 'Betel leaves', 'Ghee', 'Coconuts', 'Sweets'],
    priceRange: { min: 11000, max: 45000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['marriage', 'wedding', 'shaadi', 'matrimony', 'sacred vows', 'saptapadi']
  },
  {
    pujaName: 'Satyanarayan Puja & Katha',
    slug: 'satyanarayan-puja-katha',
    category: 'Marriage & Family Rituals',
    description: 'Dedicated to Lord Vishnu (Satyanarayan), performed by families on Purnima (full moon days) and during major lifecycle events for peace, wellness, and prosperity.',
    duration: '2.5-3.5 hours',
    requiredMaterials: ['Panchamrit', 'Banana leaves', 'Wheat flour prasad', 'Flowers', 'Fruits', 'Coconut', 'Yellow clothes', 'Incense'],
    priceRange: { min: 2100, max: 5500 },
    locationType: 'Home',
    featured: true,
    popular: true,
    searchKeywords: ['vishnu katha', 'satyanarayan', 'purnima puja', 'family peace', 'prosperity']
  },
  {
    pujaName: 'Sagai (Engagement Ceremony)',
    slug: 'sagai-engagement-ceremony',
    category: 'Marriage & Family Rituals',
    description: 'The formal engagement ceremony in Hindu culture, where couples exchange rings and families exchange gifts, sanctified by prayers to Lord Ganesha and Varuna.',
    duration: '2 hours',
    requiredMaterials: ['Rings', 'Sweets', 'Fruits', 'Kumkum', 'Roli', 'Coconut', 'Flowers', 'Red cloth'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['engagement', 'ring ceremony', 'sagai', 'mangni', 'pre-wedding']
  },
  {
    pujaName: 'Gauri Shankar Puja',
    slug: 'gauri-shankar-puja',
    category: 'Marriage & Family Rituals',
    description: 'Conducted for marital harmony, seeking the blessings of Lord Shiva and Goddess Parvati (Gauri) to remove misunderstandings and ensure longevity of the marriage.',
    duration: '2 hours',
    requiredMaterials: ['Shiva Parvati idol/photo', 'Red dupatta', 'Flowers', 'Fruits', 'Sindoor', 'Betel nuts', 'Sweets'],
    priceRange: { min: 2200, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['marriage harmony', 'shiva parvati', 'marital peace', 'stop divorce', 'relationship']
  },
  {
    pujaName: 'Roka Ceremony Puja',
    slug: 'roka-ceremony-puja',
    category: 'Marriage & Family Rituals',
    description: 'The first step towards a wedding where both families declare their consent. Sacred hymns and Ganesh prayers are held to bless the alliance.',
    duration: '1-1.5 hours',
    requiredMaterials: ['Dry fruits', 'Sweets', 'Coconut', 'Kumkum', 'Rice', 'Red thread', 'Flowers'],
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['roka', 'alliance', 'marriage consent', 'pre wedding']
  },
  {
    pujaName: 'Varshik Shraddh',
    slug: 'varshik-shraddh',
    category: 'Marriage & Family Rituals',
    description: 'An annual ritual to pay respects to deceased parents or ancestors. Helps cross over wandering souls and brings peace and descendants blessings to the family.',
    duration: '2-3 hours',
    requiredMaterials: ['Black sesame seeds', 'Barley', 'Rice balls (Pinda)', 'White flowers', 'Kusha grass', 'Ghee', 'Honey'],
    priceRange: { min: 2500, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['ancestor worship', 'death anniversary', 'pinda daan', 'shraddha', 'pitru']
  },
  {
    pujaName: 'Kanya Daan Ceremony',
    slug: 'kanya-daan-ceremony',
    category: 'Marriage & Family Rituals',
    description: 'The highly emotional wedding ritual of "giving away the daughter" to the groom, symbolizing transfer of responsibility and generation of high spiritual merits.',
    duration: '1 hour',
    requiredMaterials: ['Holy water pot', 'Gold ornament', 'Saffron', 'Rice', 'Flowers', 'Betel leaves'],
    priceRange: { min: 3000, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kanyadaan', 'wedding gift', 'wedding ritual', 'daughter wedding']
  },
  {
    pujaName: 'Manglik Dosh Nivaran Puja',
    slug: 'manglik-dosh-nivaran-puja',
    category: 'Marriage & Family Rituals',
    description: 'Conducted for individuals with Mars (Mangal) in unfavorable houses, which delays marriage or creates compatibility issues, to enable a happy marriage.',
    duration: '3 hours',
    requiredMaterials: ['Red flowers', 'Jaggery', 'Masoor dal', 'Copper metal', 'Havan Samagri', 'Red cloth'],
    priceRange: { min: 4500, max: 9500 },
    locationType: 'Both',
    featured: true,
    popular: false,
    searchKeywords: ['mangal dosh', 'manglik', 'mars cancellation', 'delay in marriage', 'horoscope']
  },
  {
    pujaName: 'Vat Savitri Vrat Puja',
    slug: 'vat-savitri-vrat-puja',
    category: 'Marriage & Family Rituals',
    description: 'Performed by married women, praying for the long life and health of their husbands by tying sacred threads around a Banyan tree.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Banyan tree thread', 'Wet chickpeas', 'Sweets', 'Fruits', 'Sindoor', 'Bangles', 'Red thread'],
    priceRange: { min: 1100, max: 2500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['husband long life', 'savitri vrat', 'banyan tree', 'married women']
  },

  // ── 3. Child & Sanskar Ceremonies (10) ──
  {
    pujaName: 'Naamkaran Sanskar',
    slug: 'naamkaran-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The traditional naming ceremony for a newborn, typically performed on the 11th or 12th day after birth to invite positive astrological vibrations.',
    duration: '2 hours',
    requiredMaterials: ['Honey', 'Ghee', 'Sacred thread', 'New baby clothes', 'Rice grains', 'Betel leaves', 'Flowers', 'Ganesh photo'],
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Home',
    featured: false,
    popular: true,
    searchKeywords: ['naming ceremony', 'newborn baby', 'naming child', 'naamkaran', 'sanskar']
  },
  {
    pujaName: 'Mundan Sanskar (Tonsure)',
    slug: 'mundan-sanskar-tonsure',
    category: 'Child & Sanskar Ceremonies',
    description: 'The first shaving of a child\'s hair (tonsure) to cleanse the child from past-life karma and stimulate healthy brain and hair growth.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Turmeric paste', 'Curd', 'Honey', 'Barber\'s new razor', 'Coconut', 'Flowers', 'Panchamrit'],
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['tonsure', 'baby haircut', 'shaving head', 'mundan', 'child ceremony']
  },
  {
    pujaName: 'Upanayana (Janeu Ceremony)',
    slug: 'upanayana-janeu-ceremony',
    category: 'Child & Sanskar Ceremonies',
    description: 'The sacred thread ceremony marking the initiation of a young boy into formal education and spiritual responsibilities under Vedic traditions.',
    duration: '4-5 hours',
    requiredMaterials: ['Janeu threads', 'Deer skin seat', 'Alms bag', 'Wood for Havan', 'New yellow garments', 'Sandalwood'],
    priceRange: { min: 7500, max: 15000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['sacred thread', 'janeu', 'upanayan', 'spiritual initiation', 'boy ceremony']
  },
  {
    pujaName: 'Annaprashan Sanskar',
    slug: 'annaprashan-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The ceremony marking the infant\'s first intake of solid food (typically sweet rice pudding or kheer), invoking nutritional health and digestion.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Silver bowl & spoon', 'Kheer (rice pudding)', 'Honey', 'Ganga water', 'Flowers', 'Ganesh Puja kit'],
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['first solid food', 'feeding baby', 'kheer feeding', 'annaprashan']
  },
  {
    pujaName: 'Garbh Sanskar / Seemantonayana',
    slug: 'garbh-sanskar-seemantonayana',
    category: 'Child & Sanskar Ceremonies',
    description: 'A baby shower-like Vedic ceremony performed during pregnancy to bless the expectant mother and invite healthy, intelligent, and positive qualities in the fetus.',
    duration: '2.5 hours',
    requiredMaterials: ['Red saree', 'Fruits', 'Sweets', 'Havan items', 'Aromatic oils', 'Coconut', 'Ghee'],
    priceRange: { min: 3000, max: 6000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['pregnancy puja', 'baby shower', 'garbh sanskar', 'safe delivery', 'mother blessing']
  },
  {
    pujaName: 'Karnavedha Sanskar',
    slug: 'karnavedha-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The ear-piercing ceremony for children, believed to improve memory power, physical health, and protect from diseases.',
    duration: '1 hour',
    requiredMaterials: ['Gold/silver needle', 'Coconut oil', 'Turmeric', 'Cotton', 'Flowers', 'Sweets'],
    priceRange: { min: 1100, max: 2500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['ear piercing', 'karnavedha', 'earlobe piercing', 'child health']
  },
  {
    pujaName: 'Vidyarambh Sanskar',
    slug: 'vidyarambh-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'Initiation of writing letters and learning. Children write their first letters in a tray of rice grains, seeking blessings of Goddess Saraswati.',
    duration: '1-1.5 hours',
    requiredMaterials: ['Slate/Notebook', 'Chalk/Pen', 'Rice grains tray', 'Saraswati photo', 'White flowers', 'Modak'],
    priceRange: { min: 1200, max: 2800 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['starting school', 'education start', 'saraswati write', 'vidyarambh']
  },
  {
    pujaName: 'Jatakarma Sanskar',
    slug: 'jatakarma-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'A birth ritual performed immediately after the child is born to welcome the infant, where the father feeds a drop of ghee and honey to the baby.',
    duration: '1 hour',
    requiredMaterials: ['Pure forest honey', 'Desi cow ghee', 'Gold stick/spoon', 'Gangajal', 'Dharba grass'],
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['birth ritual', 'father feeding', 'jatakarma', 'newborn baby']
  },
  {
    pujaName: 'Nishkramana Sanskar',
    slug: 'nishkramana-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'The child\'s first formal outing into the open air and sunlight, typically done in the 3rd or 4th month to worship the Sun and Moon.',
    duration: '1-1.5 hours',
    requiredMaterials: ['Sun/Moon photos', 'Conch shell', 'Curd', 'Honey', 'Rice grains', 'Fresh flowers'],
    priceRange: { min: 1200, max: 2500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['first outing', 'sun worship', 'moon worship', 'nishkramana']
  },
  {
    pujaName: 'Chudakarana Sanskar',
    slug: 'chudakarana-sanskar',
    category: 'Child & Sanskar Ceremonies',
    description: 'Performed to shave the child\'s head leaving a single tuft of hair (chuda/shikha) at the crown, which guards the brain\'s spiritual energy center.',
    duration: '1.5 hours',
    requiredMaterials: ['Kusha grass', 'Turmeric powder', 'Sandalwood', 'Ghee', 'Barber tools', 'New yellow cloth'],
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['shikha tuft', 'chudakarana', 'tonsure hair', 'spiritual health']
  },

  // ── 4. Business & Career Pujas (8) ──
  {
    pujaName: 'Business Ganesh Puja',
    slug: 'business-ganesh-puja',
    category: 'Business & Career Pujas',
    description: 'Dedicated to Lord Ganesha, this puja removes startup hurdles, protects business assets from litigation/losses, and boosts profitability.',
    duration: '2 hours',
    requiredMaterials: ['Ganesh Idol', 'Durva grass', 'Modak sweets', 'Red flowers', 'Coconut', 'Betel leaves', 'Attar perfume'],
    priceRange: { min: 2100, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['business start', 'ganesha business', 'remove blocks', 'profit puja', 'ganesh puja']
  },
  {
    pujaName: 'Lakshmi Kuber Puja',
    slug: 'lakshmi-kuber-puja',
    category: 'Business & Career Pujas',
    description: 'Invokes Goddess Lakshmi and Lord Kuber (treasurer of gods) to bring cash flow, wealth accumulation, and financial security to individuals and businesses.',
    duration: '2.5-3 hours',
    requiredMaterials: ['Kuber Yantra', 'Lakshmi silver coin', 'Lotus flowers', 'Perfume', 'Makhana sweets', 'Clarified butter (Ghee)'],
    priceRange: { min: 3500, max: 8000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['wealth puja', 'kuber coin', 'money block', 'financial growth', 'lakshmi puja']
  },
  {
    pujaName: 'Vyapar Vriddhi Puja',
    slug: 'vyapar-vriddhi-puja',
    category: 'Business & Career Pujas',
    description: 'Specifically designed for shopkeepers and corporate office owners to attract more footfall, increase sales, and defeat competitors.',
    duration: '2 hours',
    requiredMaterials: ['Vyapar Vriddhi Yantra', 'Saffron', 'Camphor', 'Fresh fruits', 'Betel nuts', 'Incense cones'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['sales growth', 'business success', 'shop puja', 'client attraction']
  },
  {
    pujaName: 'Vishwakarma Puja',
    slug: 'vishwakarma-puja',
    category: 'Business & Career Pujas',
    description: 'Performed on Vishwakarma Jayanti to worship machines, tools, instruments, computers, and vehicles. It ensures working safety and prevents machinery breakdowns.',
    duration: '1.5-2.5 hours',
    requiredMaterials: ['Vishwakarma photo', 'Tools/Machines', 'Red-yellow threads', 'Sweets', 'Flowers', 'Incense'],
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['factory puja', 'machine worship', 'tool blessing', 'engineers day', 'industrial']
  },
  {
    pujaName: 'Saraswati Puja for Career',
    slug: 'saraswati-puja-for-career',
    category: 'Business & Career Pujas',
    description: 'Ideal for students preparing for competitive exams or professionals looking for career shifts, promotions, and academic success.',
    duration: '2 hours',
    requiredMaterials: ['White clothes', 'Saraswati Idol', 'Books/Pens', 'White flowers', 'Yellow rice', 'Honey', 'Curd'],
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['exam success', 'job promotion', 'career growth', 'saraswati book', 'clear memory']
  },
  {
    pujaName: 'Shani Dev Puja for Job Stability',
    slug: 'shani-dev-puja-for-job-stability',
    category: 'Business & Career Pujas',
    description: 'Worship of Lord Shani to secure employment, safeguard against sudden layoffs, resolve disputes with seniors, and find a desired job.',
    duration: '2 hours',
    requiredMaterials: ['Mustard oil', 'Black cloth', 'Black sesame', 'Iron ring', 'Blue flowers', 'Urad dal'],
    priceRange: { min: 2100, max: 4800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['job stability', 'layoff protection', 'shani job', 'career hurdle']
  },
  {
    pujaName: 'Surya Puja for Promotion',
    slug: 'surya-puja-for-promotion',
    category: 'Business & Career Pujas',
    description: 'Dedicated to Lord Surya (Sun) to earn fame, administrative authority, government jobs, promotions, and goodwill from bosses.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Copper pot', 'Red sandalwood', 'Red flowers', 'Jaggery', 'Wheat grains', 'Roli'],
    priceRange: { min: 1800, max: 3800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['government job', 'promotion', 'authority', 'sun worship', 'fame']
  },
  {
    pujaName: 'Chandra Puja for Business Peace',
    slug: 'chandra-puja-for-business-peace',
    category: 'Business & Career Pujas',
    description: 'Performed to pacify the Moon (Chandra), which governs emotional stability and decision-making, helping business partners resolve internal conflicts.',
    duration: '2 hours',
    requiredMaterials: ['White sandalwood', 'Milk', 'Rice grains', 'Camphor', 'White lotus', 'Conch shell'],
    priceRange: { min: 2000, max: 4200 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['partner conflict', 'business peace', 'moon cooling', 'clear decision']
  },

  // ── 5. Health & Protection Pujas (9) ──
  {
    pujaName: 'Maha Mrityunjaya Jaap',
    slug: 'maha-mrityunjaya-jaap',
    category: 'Health & Protection Pujas',
    description: 'A powerful chanting of the Maha Mrityunjaya mantra dedicated to Lord Shiva, done to recover from critical illness, avert untimely death, and build life force.',
    duration: '4-5 hours',
    requiredMaterials: ['Rudraksha mala', 'Bel leaves', 'Milk', 'Honey', 'Ghee', 'Incense', 'Havan wood', 'Black sesame'],
    priceRange: { min: 5500, max: 15000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['health recovery', 'cure illness', 'shiva health', 'mrityunjay', 'long life', 'protection']
  },
  {
    pujaName: 'Dhanvantari Puja',
    slug: 'dhanvantari-puja',
    category: 'Health & Protection Pujas',
    description: 'Worship of Lord Dhanvantari, the physician of gods and source of Ayurveda, for relief from chronic body pains, mental health disorders, and physical ailments.',
    duration: '2 hours',
    requiredMaterials: ['Dhanvantari photo', 'Yellow flowers', 'Tulsi leaves', 'Medicinal herbs', 'Honey', 'Yellow cloth'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['ayurveda god', 'healing body', 'chronic pain', 'doctor blessing', 'dhanwantari']
  },
  {
    pujaName: 'Ayushya Homam',
    slug: 'ayushya-homam',
    category: 'Health & Protection Pujas',
    description: 'Performed on birthdays (especially of kids and elderly) to seek the blessings of the God of Life (Ayur Devata) for longevity, vitality, and good health.',
    duration: '2.5-3 hours',
    requiredMaterials: ['Havan Samagri', 'Rice', 'Ghee', 'Fruits', 'Special herbs mix', 'Durva grass'],
    priceRange: { min: 3100, max: 6500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['birthday homa', 'longevity', 'vitality', 'ayushya', 'elderly health']
  },
  {
    pujaName: 'Durga Kavach Path',
    slug: 'durga-kavach-path',
    category: 'Health & Protection Pujas',
    description: 'Recitation of the armor of Goddess Durga (Kavach) to create a protective spiritual shield around the devotee, keeping away accidents, evil eyes, and black magic.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Durga photo', 'Red flowers', 'Lemon garland', 'Camphor', 'Sweets', 'Sindoor'],
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['protective shield', 'evil eye', 'black magic removal', 'durga armor', 'accident safety']
  },
  {
    pujaName: 'Hanuman Chalisa Path & Puja',
    slug: 'hanuman-chalisa-path-puja',
    category: 'Health & Protection Pujas',
    description: 'Chanting of Hanuman Chalisa 108 times, invoking Lord Hanuman for physical strength, courage, mental sanity, and removal of ghosts/fears.',
    duration: '2.5-3.5 hours',
    requiredMaterials: ['Hanuman idol', 'Sindoor (orange)', 'Jasmine oil', 'Laddoo sweets', 'Basil leaves', 'Red flag'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['courage', 'strength', 'hanuman chalisa', 'fear removal', 'bajrang bali']
  },
  {
    pujaName: 'Sudarshana Homam',
    slug: 'sudarshana-homam',
    category: 'Health & Protection Pujas',
    description: 'A fire ritual dedicated to Lord Sudarshana (Vishnu\'s weapon disc) to purge evil forces, negative vibrations, curses, and malicious operations of enemies.',
    duration: '3.5-4 hours',
    requiredMaterials: ['Sudarshana Yantra', 'Red roses', 'Havan herbs', 'Ghee', 'Pineapple fruits', 'Camphor'],
    priceRange: { min: 5000, max: 11000 },
    locationType: 'Both',
    featured: true,
    popular: false,
    searchKeywords: ['enemy removal', 'curse removal', 'weapon disc', 'sudarshana chakra', 'heavy havan']
  },
  {
    pujaName: 'Bagalamukhi Puja for Victory',
    slug: 'bagalamukhi-puja-for-victory',
    category: 'Health & Protection Pujas',
    description: 'Dedicated to Goddess Bagalamukhi (one of the Mahavidyas) to silence enemies, win legal court cases, and overcome stiff competitions.',
    duration: '3 hours',
    requiredMaterials: ['Yellow cloth', 'Yellow flowers', 'Turmeric roots', 'Yellow sweets', 'Bagalamukhi photo'],
    priceRange: { min: 5500, max: 12000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['win court case', 'legal victory', 'silence enemies', 'yellow goddess', 'baglamukhi']
  },
  {
    pujaName: 'Rahu Ketu Shanti Puja',
    slug: 'rahu-ketu-shanti-puja',
    category: 'Health & Protection Pujas',
    description: 'Performed to mitigate the malefic effects of Rahu and Ketu in the chart, which cause mystery illnesses, toxic relationships, and sudden financial declines.',
    duration: '2.5 hours',
    requiredMaterials: ['Black mustard', 'Sesame seeds', 'Lead representations', 'Coconut', 'Two-colored flowers'],
    priceRange: { min: 3100, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['rahu ketu dosh', 'shadow planets', 'mystery illness', 'toxic relationship']
  },
  {
    pujaName: 'Kaal Sarp Dosh Nivaran Puja',
    slug: 'kaal-sarp-dosh-nivaran-puja',
    category: 'Health & Protection Pujas',
    description: 'A specialized Vedic ritual to relieve people whose astrological charts have all planets trapped between Rahu and Ketu, ensuring life stability.',
    duration: '3-4 hours',
    requiredMaterials: ['Silver snake pair', 'Rahu Ketu Yantra', 'Black sesame', 'Milk', 'Honey', 'Flowing water accessory'],
    priceRange: { min: 4500, max: 9000 },
    locationType: 'Temple',
    featured: false,
    popular: true,
    searchKeywords: ['kaal sarp', 'snake curse', 'life stability', 'rahu ketu cancel']
  },

  // ── 6. Festival Pujas (12) ──
  {
    pujaName: 'Diwali Lakshmi Puja',
    slug: 'diwali-lakshmi-puja',
    category: 'Festival Pujas',
    description: 'Performed on Amavasya during Diwali. This puja invites wealth, luck, and brightness to homes and commercial setups for the upcoming year.',
    duration: '2-2.5 hours',
    requiredMaterials: ['Lakshmi-Ganesh clay idols', 'Clay diyas', 'Silver coin', 'Kori shells', 'Lotus seeds', 'Sweets (Kaju katli)'],
    priceRange: { min: 3000, max: 6500 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['diwali', 'lakshmi puja', 'deepavali', 'wealth invitation', 'new year business']
  },
  {
    pujaName: 'Ganesh Chaturthi Puja',
    slug: 'ganesh-chaturthi-puja',
    category: 'Festival Pujas',
    description: 'Celebrated during the Ganesh festival. Involves installing the clay idol of Ganesha, reciting stories, offering modaks, and requesting wisdom.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Ganesh clay idol', 'Modaks (21)', 'Durva grass', 'Red flowers', 'Jaggery', 'Incense', 'Coconut'],
    priceRange: { min: 2100, max: 5000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['ganeshutsav', 'ganpati sthapana', 'chaturthi', 'clay ganesha', 'modak offering']
  },
  {
    pujaName: 'Durga Puja / Ghatasthapana',
    slug: 'durga-puja-ghatasthapana',
    category: 'Festival Pujas',
    description: 'Performed on the first day of Navratri. Involves installing the holy pot (Kalash/Ghata) representing Goddess Durga, sowing barley seeds, and reciting prayers.',
    duration: '2.5 hours',
    requiredMaterials: ['Clay pot', 'Barley seeds', 'Clean mud', 'Kalash water', 'Durga photo', 'Saptadhanya (7 grains)'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['navratri start', 'ghat sthapana', 'kalash installation', 'durga puja', 'nine nights']
  },
  {
    pujaName: 'Maha Shivratri Puja',
    slug: 'maha-shivratri-puja',
    category: 'Festival Pujas',
    description: 'Performed on Shivratri night, involving the continuous Abhishek of Shiva Lingam with milk, honey, sugarcane juice, and bel leaves to grant wish-fulfillment.',
    duration: '3 hours',
    requiredMaterials: ['Shiva Lingam', 'Bel leaves', 'Milk', 'Curd', 'Honey', 'Bhaang', 'Dhatura flowers', 'Sugarcane juice'],
    priceRange: { min: 3100, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['shivratri abhishek', 'shiva night', 'wish fulfillment', 'dhatura', 'bhaang']
  },
  {
    pujaName: 'Krishna Janmashtami Puja',
    slug: 'krishna-janmashtami-puja',
    category: 'Festival Pujas',
    description: 'Performed at midnight on Lord Krishna\'s birthday. Involves bathing Laddu Gopal with panchamrit, placing Him in a swing, and singing bhajans.',
    duration: '2 hours',
    requiredMaterials: ['Laddu Gopal idol', 'Jhula (swing)', 'Panchamrit', 'Makhan-Mishri (butter mix)', 'Yellow clothes', 'Peacock feather'],
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['krishna birth', 'gokulashtami', 'swing lord', 'butter bhog', 'janmashtami']
  },
  {
    pujaName: 'Raksha Bandhan Puja',
    slug: 'raksha-bandhan-puja',
    category: 'Festival Pujas',
    description: 'A household prayer celebrating the bond of brothers and sisters, seeking longevity for brothers and safety for sisters.',
    duration: '1 hour',
    requiredMaterials: ['Rakhi threads', 'Roli', 'Chawal', 'Sweets', 'Diya plate', 'Coconut'],
    priceRange: { min: 1000, max: 2000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['rakhi tying', 'brother sister bond', 'family festival', 'shravan purnima']
  },
  {
    pujaName: 'Karwa Chauth Vrat Udyapan',
    slug: 'karwa-chauth-vrat-udyapan',
    category: 'Festival Pujas',
    description: 'The closing ceremony (Udyapan) of Karwa Chauth fasts. Married women offer gifts and foods to other women and seek blessings for marital union.',
    duration: '2 hours',
    requiredMaterials: ['Clay pots (Karwa)', 'Sringar kit (makeup)', 'Sweets', 'Saree gift', 'Dry fruits', 'Sindoor'],
    priceRange: { min: 2500, max: 5000 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['karva chauth', 'fasting end', 'udyapan', 'married women gifts']
  },
  {
    pujaName: 'Chhath Puja Surya Arghya',
    slug: 'chhath-puja-surya-arghya',
    category: 'Festival Pujas',
    description: 'The offering of water and prasad (Arghya) to the setting and rising Sun on river banks, praying for the wellbeing of children and family.',
    duration: '2 hours',
    requiredMaterials: ['Soop (bamboo tray)', 'Thekua sweets', 'Cane stalks', 'Raddish', 'Coconut', 'Vermillion'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['chhath puja', 'sun setting', 'river bank', 'thekua prasad', 'bihar festival']
  },
  {
    pujaName: 'Holi Dahan Puja',
    slug: 'holi-dahan-puja',
    category: 'Festival Pujas',
    description: 'Performed in the evening before playing colors. Worshiping the bonfire (Holika) to burn down illness, greed, and negative habits.',
    duration: '1-1.5 hours',
    requiredMaterials: ['Cow dung beads', 'Thread', 'Raw cotton', 'Jaggery', 'Turmeric', 'Coconut', 'Water pot'],
    priceRange: { min: 1500, max: 3000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['holika dahan', 'bonfire puja', 'good over evil', 'spring festival']
  },
  {
    pujaName: 'Makar Sankranti Surya Tarpan',
    slug: 'makar-sankranti-surya-tarpan',
    category: 'Festival Pujas',
    description: 'A transit day puja thanking the Sun God for rich crops, involving the offering of sesame seeds and water (Tarpan).',
    duration: '1 hour',
    requiredMaterials: ['Black sesame', 'Copper pot', 'Rice', 'Jaggery sweets', 'Wheat', 'Yellow flowers'],
    priceRange: { min: 1200, max: 2500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['sun transit', 'sankranti', 'sesame offering', 'kite festival']
  },
  {
    pujaName: 'Hanuman Jayanti Sundarkand Path',
    slug: 'hanuman-jayanti-sundarkand-path',
    category: 'Festival Pujas',
    description: 'Chanting of the Sundarkand chapter from Ramayana on Hanuman\'s birthday, resolving psychological issues and building confidence.',
    duration: '3 hours',
    requiredMaterials: ['Sundarkand books', 'Boondi sweets', 'Jasmine oil', 'Sindoor', 'Red clothes', 'Fruits'],
    priceRange: { min: 2500, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['hanuman birthday', 'sundarkand path', 'ramayana reading', 'mental health boost']
  },
  {
    pujaName: 'Ram Navami Havan',
    slug: 'ram-navami-havan',
    category: 'Festival Pujas',
    description: 'Celebrated on Lord Rama\'s birthday, executing a Havan with the recitation of Rama Raksha Stotra to establish righteousness (Dharma) at home.',
    duration: '2.5 hours',
    requiredMaterials: ['Rama photo', 'Havan Kund', 'Ghee', 'Panchamrit', 'Kheer sweet', 'Sandal paste'],
    priceRange: { min: 2500, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['rama birth', 'ram navami', 'dharma establishment', 'family safety']
  },

  // ── 7. Shiva Pujas (8) ──
  {
    pujaName: 'Rudrabhishek Puja',
    slug: 'rudrabhishek-puja',
    category: 'Shiva Pujas',
    description: 'A sacred bathing ritual of Shiva Lingam chanting Sri Rudram Vedic mantras. It bestows spiritual elevation, cleanses past sins, and grants prosperity.',
    duration: '2.5-3.5 hours',
    requiredMaterials: ['Shiva Lingam', 'Milk', 'Curd', 'Honey', 'Ghee', 'Sugar', 'Bel leaves', 'Sugarcane juice', 'Sandal paste'],
    priceRange: { min: 3100, max: 7500 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['mahadev', 'shiva', 'rudra', 'abhishek', 'rudrabhishek', 'cleansing']
  },
  {
    pujaName: 'Laghu Rudra Puja',
    slug: 'laghu-rudra-puja',
    category: 'Shiva Pujas',
    description: 'An advanced Shiva Puja involving 121 recitations of Sri Rudram and Havan, conducted by multiple pandits to resolve severe planetary delays and illness.',
    duration: '5-6 hours',
    requiredMaterials: ['11 Rudraksha malas', 'Large Havan kund', 'Huge quantities of ghee', 'Bel leaves (1008)', 'Fruits'],
    priceRange: { min: 15000, max: 35000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['heavy shiva', 'multi pandit', 'rudram recitation', 'planetary cancellation']
  },
  {
    pujaName: 'Maha Rudra Puja',
    slug: 'maha-rudra-puja',
    category: 'Shiva Pujas',
    description: 'One of the ultimate rituals for Lord Shiva involving 1331 recitations of Rudram, bringing absolute protection and massive spiritual elevation to communities.',
    duration: '8-10 hours',
    requiredMaterials: ['Massive havan kund', 'Special herbs', '11 Pandits team', 'Dhoti clothes', 'Panchamrit barrels'],
    priceRange: { min: 51000, max: 125000 },
    locationType: 'Both',
    featured: true,
    popular: false,
    searchKeywords: ['ultimate shiva', 'yajna', '11 pandits', 'community blessing']
  },
  {
    pujaName: 'Shiva Sahasranama Archana',
    slug: 'shiva-sahasranama-archana',
    category: 'Shiva Pujas',
    description: 'Chanting of 1000 names of Lord Shiva while offering flowers or bel leaves on the Shiva Lingam, bringing focus, wisdom, and peace.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Bel leaves (1000)', 'Flowers', 'Shiva Lingam', 'Sandalwood paste', 'Incense', 'Sweets'],
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['1000 shiva names', 'archana', 'bel path', 'focus boost']
  },
  {
    pujaName: 'Somvar Vrat Udyapan',
    slug: 'somvar-vrat-udyapan',
    category: 'Shiva Pujas',
    description: 'The formal completion puja of Solah Somvar (16 Mondays) fasts. Couples or singles perform it to find a desired life partner or resolve marital issues.',
    duration: '2.5 hours',
    requiredMaterials: ['White cloth', 'Churma prasad', 'White flowers', 'Janeu', 'Shiva Parvati idol', 'Coconut'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['solah somvar', '16 mondays', 'find husband', 'vrat end']
  },
  {
    pujaName: 'Pradosh Vrat Puja',
    slug: 'pradosh-vrat-puja',
    category: 'Shiva Pujas',
    description: 'Performed during twilight on Trayodashi (13th lunar day) to clean negative planetary karmas and build mental peace.',
    duration: '1.5-2 hours',
    requiredMaterials: ['Lord Shiva photo', 'Bhilva leaves', 'Milk', 'Honey', 'Camphor', 'Sesame oil lamp'],
    priceRange: { min: 1500, max: 3500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['trayodashi', 'twilight prayer', 'karmic clearing', 'pradosham']
  },
  {
    pujaName: 'Kedarnath Gauri Shankar Archana',
    slug: 'kedarnath-gauri-shankar-archana',
    category: 'Shiva Pujas',
    description: 'Worshiping Lord Shiva and Gauri, drawing energy patterns from Kedarnath shrines, for removing bad luck and bringing early marriage compatibility.',
    duration: '2 hours',
    requiredMaterials: ['Kedarnath photo', 'Red and white threads', 'Sweets', 'Panchamrit', 'Bel leaves', 'Lotus'],
    priceRange: { min: 2200, max: 4800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kedarnath', 'gauri shankar', 'marriage compatibility', 'early marriage']
  },
  {
    pujaName: 'Bilvapatra Archana',
    slug: 'bilvapatra-archana',
    category: 'Shiva Pujas',
    description: 'A continuous offering of three-leaf bilvapatra (Bel leaves) to Shiva, symbolizing the three attributes (Sattva, Rajas, Tamas) to gain self-realization.',
    duration: '1.5 hours',
    requiredMaterials: ['Fresh green Bel leaves (108)', 'Sandalwood paste', 'Shiva Lingam', 'Incense', 'Ghee lamp'],
    priceRange: { min: 1200, max: 2800 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['bel leaves', 'three leaf', 'self realization', 'simple shiva']
  },

  // ── 8. Vishnu Pujas (8) ──
  {
    pujaName: 'Vishnu Sahasranama Path',
    slug: 'vishnu-sahasranama-path',
    category: 'Vishnu Pujas',
    description: 'Chanting of the 1000 names of Lord Maha Vishnu. Highly effective for reducing planetary stress (especially of Saturn and Mercury) and mental anxieties.',
    duration: '2 hours',
    requiredMaterials: ['Vishnu photo', 'Tulsi leaves', 'Yellow flowers', 'Sweets', 'Camphor', 'Sandalwood paste'],
    priceRange: { min: 1800, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['1000 vishnu names', 'tulsi offering', 'mercury stress', 'anxiety relief', 'shanti']
  },
  {
    pujaName: 'Shaligram Puja',
    slug: 'shaligram-puja',
    category: 'Vishnu Pujas',
    description: 'Bathing and worshiping the sacred Shaligram stone (representing Vishnu) with Tulsi water, bringing righteousness and removing negative ancestral defects (Pitra dosh).',
    duration: '1.5-2 hours',
    requiredMaterials: ['Shaligram stone', 'Tulsi leaves', 'Milk', 'Conch shell', 'Yellow silk cloth', 'Sandalwood'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['shaligram', 'conch shell', 'pitra dosh', 'tulsi water', 'righteousness']
  },
  {
    pujaName: 'Purushottam Maas Puja',
    slug: 'purushottam-maas-puja',
    category: 'Vishnu Pujas',
    description: 'Conducted during the leap month (Adhik Maas) dedicated to Lord Purushottam (Vishnu). Amplifies the benefits of charity, prayers, and cleanses deep-seated karmas.',
    duration: '3 hours',
    requiredMaterials: ['Adhik maas book', 'Deep (lamps) 33 numbers', 'Malpua sweets', 'Yellow clothes', 'Tulsi'],
    priceRange: { min: 3500, max: 7500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['adhik maas', 'leap month', 'purushottam', 'karma cleanse', 'malpua bhog']
  },
  {
    pujaName: 'Anant Chaturdashi Puja',
    slug: 'anant-chaturdashi-puja',
    category: 'Vishnu Pujas',
    description: 'Worshiping Lord Ananta (the infinite form of Vishnu) and tying a sacred 14-knot thread on the arm to gain infinite protection and recovery of lost fortune.',
    duration: '2.5 hours',
    requiredMaterials: ['Anant thread (14 knots)', '14 wheat flour purls', 'Vishnu photo', 'Flowers', 'Panchamrit'],
    priceRange: { min: 2200, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['ananta thread', 'infinite protection', '14 knots', 'lost fortune', 'chaturdashi']
  },
  {
    pujaName: 'Rama Raksha Stotra Path',
    slug: 'rama-raksha-stotra-path',
    category: 'Vishnu Pujas',
    description: 'A powerful prayer composed by Saint Budha Kaushika, seeking the defensive shielding of Lord Rama to fight off legal issues, fear of ghosts, and enemies.',
    duration: '1.5 hours',
    requiredMaterials: ['Rama family photo', 'Red thread', 'Rice grains', 'Betel leaves', 'Laddoo sweets'],
    priceRange: { min: 1500, max: 3200 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['rama protection', 'stotra path', 'court issue', 'fear removal']
  },
  {
    pujaName: 'Gita Path Puja',
    slug: 'gita-path-puja',
    category: 'Vishnu Pujas',
    description: 'Reading of selected chapters of Bhagavad Gita, invoking Lord Krishna to clear mental confusion, guide career pathing, and grant spiritual discrimination.',
    duration: '2 hours',
    requiredMaterials: ['Bhagavad Gita book', 'Yellow flower garland', 'Incense', 'Ghee lamp', 'Sweets'],
    priceRange: { min: 1800, max: 3800 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['bhagavad gita', 'krishna guidance', 'discrimination', 'clear confusion']
  },
  {
    pujaName: 'Venkateswara Balaji Kalyanotsavam',
    slug: 'venkateswara-balaji-kalyanotsavam',
    category: 'Vishnu Pujas',
    description: 'The ceremonial wedding ritual of Lord Venkateswara with Sridevi and Bhudevi, bringing massive financial fortunes, business expansions, and general wellbeing.',
    duration: '3.5-4.5 hours',
    requiredMaterials: ['Balaji photo/idol', 'Silk garlands', 'Makhana sweets', 'Special havan herbs', 'Saffron', 'Camphor'],
    priceRange: { min: 5500, max: 12500 },
    locationType: 'Both',
    featured: true,
    popular: false,
    searchKeywords: ['tirupati balaji', 'kalyanam', 'financial abundance', 'sridevi bhudevi']
  },
  {
    pujaName: 'Gajendra Moksha Path',
    slug: 'gajendra-moksha-path',
    category: 'Vishnu Pujas',
    description: 'Recitation of the chapter from Srimad Bhagavatam where Vishnu saves Gajendra (elephant) from a crocodile, performed to release people from debt traps and severe financial crises.',
    duration: '2 hours',
    requiredMaterials: ['Vishnu flying on Garuda photo', 'Tulsi', 'Yellow flowers', 'Curd', 'Panchamrit'],
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['debt trap', 'financial crisis', 'gajendra', 'crocodile escape', 'heavy relief']
  },

  // ── 9. Devi Pujas (8) ──
  {
    pujaName: 'Chandi Path (Durga Saptashati)',
    slug: 'chandi-path-durga-saptashati',
    category: 'Devi Pujas',
    description: 'Reading of the 700 verses of Durga Saptashati. Powerful for overcoming powerful enemies, resolving severe court matters, and obtaining name and fame.',
    duration: '4-5 hours',
    requiredMaterials: ['Saptashati book', 'Durga photo', 'Sringaar kit', 'Red flowers', 'Ghee', 'Panchamrit', 'Lemon garland'],
    priceRange: { min: 5100, max: 12000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['durga path', 'saptashati', 'chandi', 'enemy victory', 'court success']
  },
  {
    pujaName: 'Saraswati Puja for Knowledge',
    slug: 'saraswati-puja-for-knowledge',
    category: 'Devi Pujas',
    description: 'Conducted on Vasant Panchami or general days to pray for high retention power, musical skills, artistic abilities, and deep wisdom.',
    duration: '2 hours',
    requiredMaterials: ['White flowers', 'Yellow rice', 'Pens/Notebooks', 'Saraswati photo', 'Sweets (Boondi)'],
    priceRange: { min: 1800, max: 3500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['vasant panchami', 'artistic skills', 'music blessing', 'saraswati devi']
  },
  {
    pujaName: 'Varalakshmi Vrat Puja',
    slug: 'varalakshmi-vrat-puja',
    category: 'Devi Pujas',
    description: 'Celebrated by women in South India on Fridays before Purnima in Shravana month, requesting Goddess Lakshmi to bless the family with health and gold.',
    duration: '2.5 hours',
    requiredMaterials: ['Lakshmi face mask', 'Kalash pot', 'Nine-knot thread', 'Sringaar items', 'Coconut', 'Gold coins'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['shravan friday', 'south india puja', 'married women luck', 'varalakshmi']
  },
  {
    pujaName: 'Lalita Sahasranama Archana',
    slug: 'lalita-sahasranama-archana',
    category: 'Devi Pujas',
    description: 'Chanting of 1000 names of Lalita Tripura Sundari, invoking ultimate grace, beauty, self-worth, and removing health complexes.',
    duration: '2 hours',
    requiredMaterials: ['Kumkum (red powder)', 'Red roses (1000)', 'Devi photo', 'Lotus', 'Ghee lamp', 'Sweets'],
    priceRange: { min: 2000, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kumkum archana', 'lalita devi', 'tripura sundari', 'grace', '1000 devi names']
  },
  {
    pujaName: 'Gayatri Mantra Jaap',
    slug: 'gayatri-mantra-jaap',
    category: 'Devi Pujas',
    description: 'Chanting of the sacred Gayatri Mantra (up to 10,000 times) to purify intellect, clean old karmic debris, and increase aura brightness.',
    duration: '3-4 hours',
    requiredMaterials: ['Yellow cloth seat', 'Tulsi/Sandalwood mala', 'Gangajal', 'Camphor', 'Ghee lamp'],
    priceRange: { min: 3100, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['gayatri devi', 'mantra jaap', 'aura clean', 'intellect boost']
  },
  {
    pujaName: 'Kali Puja for Removing Negativity',
    slug: 'kali-puja-for-removing-negativity',
    category: 'Devi Pujas',
    description: 'Dedicated to Goddess Maha Kali, removing bad entities, spiritual possession, fear of darkness, and heavy mental depression.',
    duration: '3 hours',
    requiredMaterials: ['Hibiscus flowers (red)', 'Lemon garland', 'Black sesame', 'Kali photo', 'Camphor', 'Mustard seeds'],
    priceRange: { min: 3500, max: 8000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['kali maa', 'darkness fear', 'depression cure', 'entities removal', 'spirits']
  },
  {
    pujaName: 'Santoshi Maa Vrat Udyapan',
    slug: 'santoshi-maa-vrat-udyapan',
    category: 'Devi Pujas',
    description: 'The closing ritual of 16 Fridays fast of Santoshi Maa, bringing peace and satisfaction, resolving family squabbles.',
    duration: '2 hours',
    requiredMaterials: ['Chickpeas and Jaggery (Chana-Gur)', 'Santoshi Maa photo', 'Sour foods prohibited', 'Sweets for children'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Home',
    featured: false,
    popular: false,
    searchKeywords: ['16 fridays', 'chana gur', 'satisfaction goddess', 'vrat end']
  },
  {
    pujaName: 'Radha Krishna Yugal Puja',
    slug: 'radha-krishna-yugal-puja',
    category: 'Devi Pujas',
    description: 'Worship of the divine couple Radha and Krishna to cultivate unconditional love, empathy, and smooth out family disputes.',
    duration: '2 hours',
    requiredMaterials: ['Radha Krishna photo', 'Flute', 'Peacock feathers', 'Tulsi', 'Yellow garments', 'Butter bhog'],
    priceRange: { min: 2000, max: 4000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['love couple', 'family dispute', 'krishna radha', 'unconditional love']
  },

  // ── 10. Navagraha Pujas (10) ──
  {
    pujaName: 'Navagraha Shanti Puja',
    slug: 'navagraha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Worship of all nine planetary deities. Essential when multiple planets are in transit or birth positions that cause life confusion and bad luck.',
    duration: '3-4 hours',
    requiredMaterials: ['Navagraha wood', '9 colored cloths', 'Navadhanya grains', '9 lamps', 'Havan Samagri', 'Ghee'],
    priceRange: { min: 3500, max: 8000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['nine planets', 'planetary peace', 'navgrah', 'luck corrector', 'shanti']
  },
  {
    pujaName: 'Shani Graha Shanti Puja',
    slug: 'shani-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'A special puja dedicated to Lord Saturn (Shani Dev) during Sade Sati, Dhayya, or weak Shani periods to minimize losses and delay times.',
    duration: '2.5 hours',
    requiredMaterials: ['Mustard oil', 'Iron nail', 'Black wool cloth', 'Blue flowers', 'Black sesame'],
    priceRange: { min: 2500, max: 5000 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['saturn shanti', 'sade sati', 'dhayya', 'shani shanti', 'losses prevent']
  },
  {
    pujaName: 'Surya Graha Shanti Puja',
    slug: 'surya-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Pacifies the Sun deity Surya to recover from body weakness, eye defects, low confidence, and friction with state authorities.',
    duration: '2 hours',
    requiredMaterials: ['Copper plate', 'Red sandalwood', 'Wheat grains', 'Ruby stone representative', 'Red flowers'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['sun shanti', 'eye defects', 'low confidence', 'government friction']
  },
  {
    pujaName: 'Chandra Graha Shanti Puja',
    slug: 'chandra-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Performed to pacify the Moon, relieving the person from depression, emotional fluctuations, water-related diseases, and mother\'s ill health.',
    duration: '2 hours',
    requiredMaterials: ['Conch', 'White rice', 'Milk', 'Sandalwood', 'Silver piece', 'White flowers'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['moon shanti', 'depression relief', 'emotional swings', 'water health']
  },
  {
    pujaName: 'Mangal Graha Shanti Puja',
    slug: 'mangal-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Pacifies Mars to solve blood disorders, intense anger issues, real estate debts, and disputes with younger brothers.',
    duration: '2.5 hours',
    requiredMaterials: ['Coral representative', 'Red lentils (Masoor)', 'Jaggery', 'Red flowers', 'Red copper pot'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['mars shanti', 'blood disorder', 'anger issues', 'brother dispute']
  },
  {
    pujaName: 'Budha Graha Shanti Puja',
    slug: 'budha-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Pacifies Mercury (Budh) to solve stammering issues, skin allergies, failures in trading, and weak mathematical calculation.',
    duration: '2 hours',
    requiredMaterials: ['Green moong dal', 'Emerald representative', 'Green cloth', 'Tulsi', 'Banana', 'Gold thread'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['mercury shanti', 'speech therapist', 'skin allergy', 'trading fail']
  },
  {
    pujaName: 'Guru Graha Shanti Puja',
    slug: 'guru-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Pacifies Jupiter (Guru) to remove blocks in conceiving children, liver problems, obesity, and delays in high education.',
    duration: '2.5 hours',
    requiredMaterials: ['Chana dal', 'Turmeric sticks', 'Yellow flowers', 'Yellow cloth', 'Saffron', 'Honey'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['jupiter shanti', 'conceiving blocks', 'liver health', 'obesity cure']
  },
  {
    pujaName: 'Shukra Graha Shanti Puja',
    slug: 'shukra-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Pacifies Venus (Shukra) to correct urinary tract infections, lack of luxury/vehicle comfort, and bad relationship with wife.',
    duration: '2 hours',
    requiredMaterials: ['White beans (Lobhia)', 'White sandalwood', 'Diamond representative', 'Camphor', 'Perfume'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['venus shanti', 'wife compatibility', 'luxury lifestyle', 'urinary issue']
  },
  {
    pujaName: 'Rahu Graha Shanti Puja',
    slug: 'rahu-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Worship to pacify Rahu, reducing risk of major scams, sudden health failures, confusion in career, and addiction tendencies.',
    duration: '2 hours',
    requiredMaterials: ['Black mustard', 'Lead coin', 'Coconut', 'Seven grains', 'Blue flowers'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['rahu shanti', 'scam prevention', 'addiction cure', 'career confusion']
  },
  {
    pujaName: 'Ketu Graha Shanti Puja',
    slug: 'ketu-graha-shanti-puja',
    category: 'Navagraha Pujas',
    description: 'Worship to pacify Ketu, preventing back pains, sudden accidents, skin diseases, and giving high spiritual focus.',
    duration: '2 hours',
    requiredMaterials: ['Sesame seeds', 'Kusha grass', 'Blanket donation representative', 'Multi-color flowers'],
    priceRange: { min: 2500, max: 5500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['ketu shanti', 'accident prevention', 'back pain', 'spiritual focus']
  },

  // ── 11. Homa & Havan Rituals (10) ──
  {
    pujaName: 'Ganapathi Homam',
    slug: 'ganapathi-homam',
    category: 'Homa & Havan Rituals',
    description: 'A sacred fire ritual dedicated to Lord Ganesha, typically performed early morning before any major lifecycle event or house movement to assure obstacle-free progress.',
    duration: '2.5-3.5 hours',
    requiredMaterials: ['Havan Kund', 'Ganesh Idol', 'Modak sweets', 'Ghee', 'Samagri pack', 'Dry coconut half', 'Turmeric', 'Flowers'],
    priceRange: { min: 3000, max: 6500 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['ganesha havan', 'morning homa', 'obstacle free', 'ganapathi homa']
  },
  {
    pujaName: 'Chandi Homam',
    slug: 'chandi-homam',
    category: 'Homa & Havan Rituals',
    description: 'A grand fire ritual dedicated to Goddess Chandi. Invokes major forces of energy to remove barriers in career, destroy negative spirits, and bring great fortune.',
    duration: '5-7 hours',
    requiredMaterials: ['Large Havan Kund', 'Dhoti garments', 'Lotus flowers', 'Dry coconut halves', 'Fruits', 'Special herbs mix', 'Red cloth'],
    priceRange: { min: 18000, max: 45000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['chandi havan', 'heavy fire ritual', 'career barrier', 'durga fire', 'fortune']
  },
  {
    pujaName: 'Navagraha Homam',
    slug: 'navagraha-homam',
    category: 'Homa & Havan Rituals',
    description: 'The fire ritual format of Navagraha Puja. The wood of nine specific trees are burned with mantras to harmonize positive fields of all 9 stars.',
    duration: '3-4 hours',
    requiredMaterials: ['Navagraha sticks', '9 grain packets', 'Ghee', 'Fruits', 'Sweets', 'Panchamrit', 'Havan samagri'],
    priceRange: { min: 4000, max: 8500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['planet fire', 'navgraha havan', 'star correction', 'woods fire']
  },
  {
    pujaName: 'Maha Mrityunjaya Homam',
    slug: 'maha-mrityunjaya-homam',
    category: 'Homa & Havan Rituals',
    description: 'The fire ritual format of Mrityunjaya mantra, offering black sesame and special durva grass to the fire to save a dying or critically ill family member.',
    duration: '4-5 hours',
    requiredMaterials: ['Rudraksha beads', 'Black sesame', 'Durva grass', 'Giloy herbs', 'Ghee', 'Wood', 'Camphor'],
    priceRange: { min: 6000, max: 15000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['critical illness fire', 'shiva fire', 'mrityunjaya havan', 'save life']
  },
  {
    pujaName: 'Saraswati Homam',
    slug: 'saraswati-homam',
    category: 'Homa & Havan Rituals',
    description: 'Fire ritual dedicated to Saraswati, allowing students preparing for tough exams to burn down memory barriers and raise mental clarity.',
    duration: '2.5 hours',
    requiredMaterials: ['White flowers', 'Lotus seeds', 'Ghee', 'Sweet rice prasad', 'Yellow fruits', 'Notebook for blessing'],
    priceRange: { min: 3000, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['education fire', 'exam boost havan', 'saraswati havan', 'memory fire']
  },
  {
    pujaName: 'Lakshmi Kuber Homam',
    slug: 'lakshmi-kuber-homam',
    category: 'Homa & Havan Rituals',
    description: 'Fire ritual offering lotus flowers dipped in honey and ghee to Goddess Lakshmi and Lord Kuber to solve bankruptcy and business losses.',
    duration: '3 hours',
    requiredMaterials: ['108 Lotus flowers', 'Honey bottle', 'Pure cow ghee', 'Kuber Yantra', 'Coins', 'Red cloth'],
    priceRange: { min: 4500, max: 9500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['money fire', 'bankruptcy solve', 'lakshmi havan', 'lotus honey']
  },
  {
    pujaName: 'Rudra Homam',
    slug: 'rudra-homam',
    category: 'Homa & Havan Rituals',
    description: 'Sacred fire ritual to pacify Lord Rudra, washing off deep ancestral curses (Pitra Dosh) and severe planetary combinations.',
    duration: '3.5 hours',
    requiredMaterials: ['Bel leaves', 'Black sesame', 'Ghee', 'Rudra samagri pack', 'White sweets', 'Coconut halves'],
    priceRange: { min: 4500, max: 9000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['rudra havan', 'ancestral curse', 'shiva fire homa']
  },
  {
    pujaName: 'Karuppasamy Homam',
    slug: 'karuppasamy-homam',
    category: 'Homa & Havan Rituals',
    description: 'A traditional Southern ritual invoking Karuppasamy (a guard deity) to provide instant justice, shield properties from grabbers, and break evil wizardries.',
    duration: '3 hours',
    requiredMaterials: ['Lemon garland', 'Camphor', 'Crude wood', 'Black threat', 'Iron weapons photos', 'Jaggery rice'],
    priceRange: { min: 4500, max: 9500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['southern fire', 'justice deity', 'karuppasamy', 'break wizardries', 'land grab shield']
  },
  {
    pujaName: 'Dhanvantari Homam',
    slug: 'dhanvantari-homam',
    category: 'Homa & Havan Rituals',
    description: 'The fire ritual format of Dhanvantari Puja, where medicinal herbs (Aushadha) are offered to the fire to build strong immunity.',
    duration: '2.5 hours',
    requiredMaterials: ['Ayurveda herbs pack', 'Ghee', 'Yellow cloth', 'Medicinal wood', 'Tulsi leaves', 'Yellow rice'],
    priceRange: { min: 3500, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['immunity fire', 'health havan', 'herbal offering', 'dhanvantri homam']
  },
  {
    pujaName: 'Karika Dahan Havan',
    slug: 'karika-dahan-havan',
    category: 'Homa & Havan Rituals',
    description: 'Performed on special Saturdays to burn down debt liabilities, offering black sesame seeds and cotton seeds to fire.',
    duration: '2 hours',
    requiredMaterials: ['Black sesame', 'Cotton seeds', 'Crude wood', 'Camphor', 'Mustard oil lamp'],
    priceRange: { min: 2100, max: 4500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['debt burn', 'saturday fire', 'sesame offering', 'financial relief']
  },

  // ── 12. Special Vedic Ceremonies (10) ──
  {
    pujaName: 'Pitra Dosh Nivaran Puja',
    slug: 'pitra-dosh-nivaran-puja',
    category: 'Special Vedic Ceremonies',
    description: 'Conducted at holy sites (like Gaya, Rameshwaram, or locally) to satisfy deceased ancestors who passed away with unfulfilled desires, restoring family expansion and peace.',
    duration: '3-4 hours',
    requiredMaterials: ['Rice flour balls (Pindas)', 'Black sesame', 'Kusha grass', 'White flowers', 'Gangajal', 'Honey', 'White dhoti clothes'],
    priceRange: { min: 4100, max: 9500 },
    locationType: 'Both',
    featured: false,
    popular: true,
    searchKeywords: ['ancestor peace', 'gaya puja', 'pitru dosh', 'family block', 'pinda daan']
  },
  {
    pujaName: 'Narayan Bali Puja',
    slug: 'narayan-bali-puja',
    category: 'Special Vedic Ceremonies',
    description: 'A highly specialized ritual for ancestors who met with accidental or unnatural deaths, freeing their trapped souls and protecting descendants from curses.',
    duration: '4-5 hours',
    requiredMaterials: ['Gold dummy body representative', 'Dharba grass', 'Large havan kit', 'Rice flour balls', 'Flowers', 'Panchamrit'],
    priceRange: { min: 6500, max: 15000 },
    locationType: 'Both',
    featured: true,
    popular: false,
    searchKeywords: ['accidental death', 'unnatural death', 'soul release', 'narayan bali', 'heavy ancestor']
  },
  {
    pujaName: 'Nakshatra Shanti Puja',
    slug: 'nakshatra-shanti-puja',
    category: 'Special Vedic Ceremonies',
    description: 'Performed to pacify the negative vibrations of the child\'s birth star (Nakshatra) if they are born in unfavorable stars like Ashlesha, Jyeshtha, or Moola.',
    duration: '3 hours',
    requiredMaterials: ['Star tree leaves', '27 wells water representative', 'Navadhanya grains', 'Sweets', 'Havan samagri'],
    priceRange: { min: 3500, max: 7500 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['birth star', 'mool shanti', 'nakshatra shanti', 'child safety star']
  },
  {
    pujaName: 'Shasti Poorthi (60th Birthday)',
    slug: 'shasti-poorthi-60th-birthday',
    category: 'Special Vedic Ceremonies',
    description: 'A grand ceremony celebrated when a person completes 60 years. Involves renewing wedding vows and executing major Abhishek/Havan for physical health.',
    duration: '4-5 hours',
    requiredMaterials: ['11 Kalash pots', 'Wedding garlands', 'New couple clothes', 'Havan wood', 'Makhana sweets', 'Red threads'],
    priceRange: { min: 8500, max: 20000 },
    locationType: 'Both',
    featured: true,
    popular: true,
    searchKeywords: ['60th birthday', 'vow renewal', 'elderly health', 'shastipoorthi', 'abhishek']
  },
  {
    pujaName: 'Sathabhishekam (80th Birthday)',
    slug: 'sathabhishekam-80th-birthday',
    category: 'Special Vedic Ceremonies',
    description: 'Celebrated when a person sees 1000 full moons (around 80 years and 8 months of age), seeking high blessings for longevity and lineage health.',
    duration: '4-5 hours',
    requiredMaterials: ['Gold flowers representation', '1000 moon representation pots', 'New clothes', 'Garlands', 'Abhishek items'],
    priceRange: { min: 11000, max: 25000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['80th birthday', '1000 moons', 'sathabhishekam', 'longevity blessing']
  },
  {
    pujaName: 'Bheema Ratha Shanthi (70th Birthday)',
    slug: 'bheema-ratha-shanthi-70th-birthday',
    category: 'Special Vedic Ceremonies',
    description: 'Celebrated at the completion of 70 years, seeking Mrityunjaya blessings and family unity.',
    duration: '4 hours',
    requiredMaterials: ['Abhishek pots', 'Garlands', 'New garments', 'Ghee', 'Fruits', 'Vedic text books'],
    priceRange: { min: 7500, max: 18000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['70th birthday', 'bheema ratha', 'mrityunjaya blessing']
  },
  {
    pujaName: 'Shat Chandi Yajna',
    slug: 'shat-chandi-yajna',
    category: 'Special Vedic Ceremonies',
    description: 'An extremely powerful, multi-day royal ritual where Chandi Path is chanted 100 times by 5 or more Pandits to bring victory, massive wealth, and public fame.',
    duration: '3 days (12-15 hours)',
    requiredMaterials: ['Grand Havan Kund', 'Team of 5 Pandits', 'Piles of wood', 'Ghee liters', 'Sringaar sets (10)', 'Huge prasads'],
    priceRange: { min: 75000, max: 200000 },
    locationType: 'Both',
    featured: true,
    popular: false,
    searchKeywords: ['shatchandi', 'royal yajna', '3 days ritual', 'public fame', '5 pandits']
  },
  {
    pujaName: 'Atirudra Maha Yajna',
    slug: 'atirudra-maha-yajna',
    category: 'Special Vedic Ceremonies',
    description: 'The ultimate fire ritual for Lord Shiva where Sri Rudram is chanted 14,641 times by a team of 111 Pandits, bringing absolute positive energy to earth.',
    duration: '11 days (30+ hours)',
    requiredMaterials: ['Massive temple-sized havan', '111 Pandits team', 'Barrels of ghee', 'Tons of woods', 'Food for community'],
    priceRange: { min: 250000, max: 750000 },
    locationType: 'Temple',
    featured: false,
    popular: false,
    searchKeywords: ['atirudra', '11 days yajna', '111 pandits', 'ultimate positive energy']
  },
  {
    pujaName: 'Nakshatra Gand Mool Shanti',
    slug: 'nakshatra-gand-mool-shanti',
    category: 'Special Vedic Ceremonies',
    description: 'A special star shanti for babies born in Gand Mool nakshatras, removing bad luck for the parents and child.',
    duration: '3 hours',
    requiredMaterials: ['27 star leaves', 'Clay pots', 'Star metals', 'Havan samagri', 'Ghee'],
    priceRange: { min: 3500, max: 7000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['gand mool', 'mool shanti', 'baby bad luck remove']
  },
  {
    pujaName: 'Shanti Karan Yajna',
    slug: 'shanti-karan-yajna',
    category: 'Special Vedic Ceremonies',
    description: 'Vedic ceremony performed to pacify planetary anomalies or home conflicts, establishing complete peace and wellness.',
    duration: '2.5 hours',
    requiredMaterials: ['Havan wood', 'Samagri', 'Ghee', 'Panchamrit', 'White flowers', 'Sandal paste'],
    priceRange: { min: 3000, max: 6000 },
    locationType: 'Both',
    featured: false,
    popular: false,
    searchKeywords: ['home conflicts', 'peace yajna', 'shanti karan']
  }
];

module.exports = ritualsData;
